# Core RTL filelist. Paths are relative to the repository root.
# Keep packages/types/interfaces before modules that import or bind them.

rtl/core/BasicTypes.sv
rtl/core/PipelineTypes.sv
rtl/core/CommitStage/RecoveryTypes.sv
rtl/core/DecodeStage/DecodeTypes.sv
rtl/core/RenameStage/RenameTypes.sv
rtl/core/DispatchStage/IssueTypes.sv
rtl/core/DispatchStage/ROBTypes.sv
rtl/core/DispatchStage/StoreBufferTypes.sv
rtl/core/ReadRegStage/ReadRegTypes.sv

rtl/core/IromAccessIF.sv
rtl/core/DramAccessIF.sv
rtl/core/DebugIF.sv
rtl/core/PerfIF.sv
rtl/core/CtrlIF.sv
rtl/core/PreFetchStage/PreFetchStageIF.sv
rtl/core/FetchStage/FetchStageIF.sv
rtl/core/DecodeStage/DecodeStageIF.sv
rtl/core/RenameStage/RenameStageIF.sv
rtl/core/RenameStage/SpecRATIF.sv
rtl/core/RenameStage/ArchRATIF.sv
rtl/core/RenameStage/FreeListIF.sv
rtl/core/RenameStage/ReadyTableIF.sv
rtl/core/DispatchStage/DIspatchStageIF.sv
rtl/core/DispatchStage/IssueQueueIF.sv
rtl/core/DispatchStage/PayloadIF.sv
rtl/core/DispatchStage/ROBIF.sv
rtl/core/DispatchStage/StoreBufferIF.sv
rtl/core/IssueStage/IssueStageIF.sv
rtl/core/ReadRegStage/ReadRegStageIF.sv
rtl/core/ReadRegStage/RegFileIF.sv
rtl/core/ExecuteStage/ExecuteStageIF.sv
rtl/core/WriteBackStage/WriteBackStageIF.sv
rtl/core/WriteBackStage/BypassIF.sv
rtl/core/CommitStage/CommitStageIF.sv
rtl/core/CommitStage/RecoveryManagerIF.sv

rtl/core/PreFetchStage/BHB.sv
rtl/core/PreFetchStage/BTB.sv
rtl/core/PreFetchStage/BPU.sv
rtl/core/PreFetchStage/PC.sv
rtl/core/PreFetchStage/PreFetchStage.sv
rtl/core/FetchStage/FetchStage.sv
rtl/core/DecodeStage/DecodeStage.sv
rtl/core/RenameStage/SpecRAT.sv
rtl/core/RenameStage/ArchRAT.sv
rtl/core/RenameStage/FreeList.sv
rtl/core/RenameStage/ReadyTable.sv
rtl/core/RenameStage/RenameStage.sv
rtl/core/DispatchStage/IssueQueue.sv
rtl/core/DispatchStage/Payload.sv
rtl/core/DispatchStage/ROB.sv
rtl/core/DispatchStage/StoreBuffer.sv
rtl/core/DispatchStage/DispatchStage.sv
rtl/core/IssueStage/IssueStage.sv
rtl/core/ReadRegStage/RegFile.sv
rtl/core/ReadRegStage/ReadRegStage.sv
rtl/core/ExecuteStage/ExecuteAluStage.sv
rtl/core/ExecuteStage/ExecuteBrcStage.sv
rtl/core/ExecuteStage/ExecuteMulStage.sv
rtl/core/ExecuteStage/ExecuteMemStage.sv
rtl/core/ExecuteStage/ExecuteSysStage.sv
rtl/core/WriteBackStage/Bypass.sv
rtl/core/WriteBackStage/WriteBackStage.sv
rtl/core/CommitStage/CommitStage.sv
rtl/core/CommitStage/RecoveryManager.sv
rtl/core/Ctrl.sv
rtl/core/core.sv
rtl/core/myCPU.sv
