`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: branch_predictor
// Generated: 2026-07-13
// Source: 053 architecture
module branch_predictor #(
    parameter int unsigned ENTRIES   = core_config_pkg::BTB_ENTRIES,
    parameter int unsigned RAS_DEPTH = core_config_pkg::RAS_DEPTH
) (
    input  logic       clk,
    input  logic       rst,
    input  logic [31:0] predict_pc_i,
    output logic [31:0] predict_next_pc_o,
    output core_types_pkg::pred_kind_e predict_kind_o,
    input  logic       update_valid_i,
    input  logic [31:0] update_pc_i,
    input  logic       update_taken_i,
    input  logic [31:0] update_target_i,
    input  core_types_pkg::pred_kind_e update_kind_i,
    input  logic       commit_call_i,
    input  logic       commit_return_i,
    input  logic [31:0] commit_link_i
);
    import core_types_pkg::*;
    localparam int unsigned INDEX_W = $clog2(ENTRIES);
    localparam int unsigned RAS_W   = $clog2(RAS_DEPTH);

    logic [ENTRIES-1:0] valid_q;
    logic [31:INDEX_W+2] tag_q [0:ENTRIES-1];
    logic [31:0] target_q [0:ENTRIES-1];
    logic [1:0] counter_q [0:ENTRIES-1];
    pred_kind_e kind_q [0:ENTRIES-1];
    logic [31:0] ras_q [0:RAS_DEPTH-1];
    logic [RAS_W:0] ras_count_q;
    logic [RAS_W-1:0] ras_top_c;
    logic [INDEX_W-1:0] pred_idx, upd_idx;
    logic pred_hit;

    assign pred_idx = predict_pc_i[INDEX_W+1:2];
    assign upd_idx  = update_pc_i[INDEX_W+1:2];
    assign pred_hit = valid_q[pred_idx] && (tag_q[pred_idx] == predict_pc_i[31:INDEX_W+2]);
    assign ras_top_c = RAS_W'(ras_count_q - 1'b1);

    always_comb begin
        predict_next_pc_o = predict_pc_i + 32'd4;
        predict_kind_o = PRED_NONE;
        if (pred_hit) begin
            predict_kind_o = kind_q[pred_idx];
            unique case (kind_q[pred_idx])
                PRED_COND: if (counter_q[pred_idx][1]) predict_next_pc_o = target_q[pred_idx];
                PRED_RETURN: begin
                    if (ras_count_q != 0) predict_next_pc_o = ras_q[ras_top_c];
                    else predict_next_pc_o = target_q[pred_idx];
                end
                PRED_JUMP: predict_next_pc_o = target_q[pred_idx];
                default: begin end
            endcase
        end
    end

    always_ff @(posedge clk) begin
        if (rst) begin
            valid_q <= '0;
            ras_count_q <= '0;
        end else begin
            if (update_valid_i) begin
                valid_q[upd_idx] <= 1'b1;
                tag_q[upd_idx] <= update_pc_i[31:INDEX_W+2];
                target_q[upd_idx] <= update_target_i;
                kind_q[upd_idx] <= update_kind_i;
                if (update_kind_i == PRED_COND) begin
                    if (!valid_q[upd_idx] || tag_q[upd_idx] != update_pc_i[31:INDEX_W+2])
                        counter_q[upd_idx] <= update_taken_i ? 2'b10 : 2'b01;
                    else if (update_taken_i && counter_q[upd_idx] != 2'b11)
                        counter_q[upd_idx] <= counter_q[upd_idx] + 1'b1;
                    else if (!update_taken_i && counter_q[upd_idx] != 2'b00)
                        counter_q[upd_idx] <= counter_q[upd_idx] - 1'b1;
                end else begin
                    counter_q[upd_idx] <= 2'b11;
                end
            end
            if (commit_call_i) begin
                if (ras_count_q < (RAS_W+1)'(RAS_DEPTH)) begin
                    ras_q[ras_count_q[RAS_W-1:0]] <= commit_link_i;
                    ras_count_q <= ras_count_q + 1'b1;
                end else begin
                    ras_q[RAS_DEPTH-1] <= commit_link_i;
                end
            end else if (commit_return_i && ras_count_q != 0) begin
                ras_count_q <= ras_count_q - 1'b1;
            end
        end
    end
endmodule
