`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: frontend
// Generated: 2026-07-13
// Source: 053 architecture
module frontend (
    input  logic clk,
    input  logic rst,
    input  logic redirect_valid_i,
    input  logic [31:0] redirect_target_i,
    output logic [31:0] irom_addr_o,
    output logic irom_ena_o,
    input  logic [31:0] irom_data_i,
    output logic fetch_valid_o,
    output core_types_pkg::fetch_entry_t fetch_entry_o,
    input  logic fetch_ready_i,
    input  logic predictor_update_valid_i,
    input  logic [31:0] predictor_update_pc_i,
    input  logic predictor_update_taken_i,
    input  logic [31:0] predictor_update_target_i,
    input  core_types_pkg::pred_kind_e predictor_update_kind_i,
    input  logic predictor_commit_call_i,
    input  logic predictor_commit_return_i,
    input  logic [31:0] predictor_commit_link_i
);
    import core_config_pkg::*;
    import core_types_pkg::*;

    localparam int unsigned COUNT_W = $clog2(FETCH_QUEUE_DEPTH + 1);
    logic [COUNT_W-1:0] queue_count;
    logic [31:0] fetch_pc_q;
    logic pending_valid_q;
    logic [31:0] pending_pc_q, pending_pred_next_q;
    pred_kind_e pending_pred_kind_q;
    logic [31:0] predicted_next_pc;
    pred_kind_e predicted_kind;
    fetch_entry_t push_entry;
    logic queue_push, queue_pop;

    branch_predictor u_branch_predictor (
        .clk(clk), .rst(rst), .predict_pc_i(fetch_pc_q),
        .predict_next_pc_o(predicted_next_pc), .predict_kind_o(predicted_kind),
        .update_valid_i(predictor_update_valid_i), .update_pc_i(predictor_update_pc_i),
        .update_taken_i(predictor_update_taken_i), .update_target_i(predictor_update_target_i),
        .update_kind_i(predictor_update_kind_i), .commit_call_i(predictor_commit_call_i),
        .commit_return_i(predictor_commit_return_i), .commit_link_i(predictor_commit_link_i)
    );

    assign irom_addr_o = fetch_pc_q;
    assign irom_ena_o = !rst && !redirect_valid_i &&
                        ((queue_count + COUNT_W'(pending_valid_q)) < COUNT_W'(FETCH_QUEUE_DEPTH));
    assign queue_push = pending_valid_q && !redirect_valid_i;
    assign queue_pop = fetch_valid_o && fetch_ready_i && !redirect_valid_i;
    always_comb begin
        push_entry = '0;
        push_entry.pc = pending_pc_q;
        push_entry.instr = irom_data_i;
        push_entry.pred_next_pc = pending_pred_next_q;
        push_entry.pred_kind = pending_pred_kind_q;
    end

    fetch_queue u_fetch_queue (
        .clk(clk), .rst(rst), .flush_i(redirect_valid_i),
        .push_i(queue_push), .push_entry_i(push_entry), .pop_i(queue_pop),
        .valid_o(fetch_valid_o), .head_o(fetch_entry_o), .count_o(queue_count)
    );

    always_ff @(posedge clk) begin
        if (rst) begin
            fetch_pc_q <= RESET_PC;
            pending_valid_q <= 1'b0;
            pending_pc_q <= '0;
            pending_pred_next_q <= '0;
            pending_pred_kind_q <= PRED_NONE;
        end else if (redirect_valid_i) begin
            fetch_pc_q <= redirect_target_i;
            pending_valid_q <= 1'b0;
        end else begin
            pending_valid_q <= irom_ena_o;
            if (irom_ena_o) begin
                pending_pc_q <= fetch_pc_q;
                pending_pred_next_q <= predicted_next_pc;
                pending_pred_kind_q <= predicted_kind;
                fetch_pc_q <= predicted_next_pc;
            end
        end
    end

`ifndef SYNTHESIS
    always_ff @(posedge clk) begin
        if (!rst) assert (queue_count + COUNT_W'(pending_valid_q) <= COUNT_W'(FETCH_QUEUE_DEPTH));
    end
`endif
endmodule
