# Late top-level CDC constraints for the two PLL output domains.
# The SoC treats clk_out1_pll (50 MHz system/twin/counter) and
# clk_out2_pll (CPU/IROM/DRAM/core) as CDC domains, even though
# both clocks are generated by the same clk_wiz instance.
set sys_clk [get_clocks -quiet clk_out1_pll]
set cpu_clk [get_clocks -quiet clk_out2_pll]
if {[llength $sys_clk] == 0} {
    set sys_clk [get_clocks -quiet -of_objects [get_pins -hier -filter {NAME =~ */clkout1_buf/O}]]
}
if {[llength $cpu_clk] == 0} {
    set cpu_clk [get_clocks -quiet -of_objects [get_pins -hier -filter {NAME =~ */clkout2_buf/O}]]
}
if {[llength $sys_clk] > 0 && [llength $cpu_clk] > 0} {
    set_clock_groups -asynchronous -group $sys_clk -group $cpu_clk
} else {
    puts "WARNING: CDC clock groups not applied; PLL output clocks were not found."
}
