`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: perf_counters
// Generated: 2026-07-13
// Source: 053 architecture
module perf_counters (
    input  logic clk,
    input  logic rst,
    input  logic commit_i,
    input  logic commit_load_i,
    input  logic commit_store_i,
    input  logic branch_i,
    input  logic branch_miss_i,
    input  logic dcache_access_i,
    input  logic dcache_miss_i,
    input  logic stall_front_i,
    input  logic stall_mem_i,
    input  logic stall_muldiv_i,
    input  logic stall_raw_i,
    output logic [63:0] cycle_o,
    output logic [63:0] commit_o,
    output logic [63:0] branch_o,
    output logic [63:0] branch_miss_o,
    output logic [63:0] load_o,
    output logic [63:0] store_o,
    output logic [63:0] dcache_access_o,
    output logic [63:0] dcache_miss_o,
    output logic [63:0] stall_front_o,
    output logic [63:0] stall_mem_o,
    output logic [63:0] stall_muldiv_o,
    output logic [63:0] stall_raw_o
);
    always_ff @(posedge clk) begin
        if (rst) begin
            cycle_o <= '0;
            commit_o <= '0;
            branch_o <= '0;
            branch_miss_o <= '0;
            load_o <= '0;
            store_o <= '0;
            dcache_access_o <= '0;
            dcache_miss_o <= '0;
            stall_front_o <= '0;
            stall_mem_o <= '0;
            stall_muldiv_o <= '0;
            stall_raw_o <= '0;
        end else begin
            cycle_o <= cycle_o + 1'b1;
            if (commit_i) commit_o <= commit_o + 1'b1;
            if (commit_load_i) load_o <= load_o + 1'b1;
            if (commit_store_i) store_o <= store_o + 1'b1;
            if (branch_i) branch_o <= branch_o + 1'b1;
            if (branch_miss_i) branch_miss_o <= branch_miss_o + 1'b1;
            if (dcache_access_i) dcache_access_o <= dcache_access_o + 1'b1;
            if (dcache_miss_i) dcache_miss_o <= dcache_miss_o + 1'b1;
            // Exactly one exported primary stall cause is counted per cycle.
            if (stall_raw_i) stall_raw_o <= stall_raw_o + 1'b1;
            else if (stall_mem_i) stall_mem_o <= stall_mem_o + 1'b1;
            else if (stall_muldiv_i) stall_muldiv_o <= stall_muldiv_o + 1'b1;
            else if (stall_front_i) stall_front_o <= stall_front_o + 1'b1;
        end
    end

`ifndef SYNTHESIS
    always_ff @(posedge clk) begin
        if (!rst) begin
            assert (commit_o <= cycle_o);
            assert (branch_miss_o <= branch_o);
            assert (dcache_miss_o <= dcache_access_o);
            assert (load_o + store_o <= commit_o);
        end
    end
`endif
endmodule
