`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: dcache
// Generated: 2026-07-13
// Source: 053 architecture
module dcache #(
    parameter int unsigned LINE_COUNT = core_config_pkg::DCACHE_LINES,
    parameter logic [31:0] CACHE_START = core_config_pkg::DRAM_START,
    parameter logic [31:0] CACHE_END   = core_config_pkg::DRAM_END
) (
    input  logic clk,
    input  logic rst,
    input  logic kill_i,
    input  logic cpu_req_valid_i,
    output logic cpu_req_ready_o,
    input  logic cpu_req_write_i,
    input  logic [31:0] cpu_req_addr_i,
    input  logic [31:0] cpu_req_wdata_i,
    input  logic [3:0] cpu_req_wstrb_i,
    input  logic cpu_req_uncached_i,
    output logic cpu_resp_valid_o,
    output logic [31:0] cpu_resp_rdata_o,
    output logic mem_req_valid_o,
    input  logic mem_req_ready_i,
    output logic mem_req_write_o,
    output logic [31:0] mem_req_addr_o,
    output logic [31:0] mem_req_wdata_o,
    output logic [3:0] mem_req_wstrb_o,
    output logic mem_req_uncached_o,
    input  logic mem_resp_valid_i,
    input  logic [31:0] mem_resp_rdata_i,
    output logic access_pulse_o,
    output logic miss_pulse_o,
    output logic idle_o
);
    localparam int unsigned INDEX_W = $clog2(LINE_COUNT);
    localparam int unsigned TAG_LSB = 4 + INDEX_W;

    typedef enum logic [2:0] {
        DC_IDLE, DC_RESP, DC_UNC_WAIT, DC_REFILL_REQ, DC_REFILL_WAIT
    } state_e;
    state_e state_q;

    logic [LINE_COUNT-1:0] valid_q;
    logic [31:TAG_LSB] tag_q [0:LINE_COUNT-1];
    logic [31:0] data_q [0:LINE_COUNT-1][0:3];
    logic [31:0] req_addr_q;
    logic [1:0] target_word_q, fill_word_q;
    logic [31:0] resp_data_q, target_data_q;
    logic killed_q;

    logic cacheable_c, hit_c;
    logic [INDEX_W-1:0] index_c;
    logic [31:TAG_LSB] tag_c;
    logic [1:0] word_c;
    logic [31:0] store_aligned_data_c;
    logic [3:0] store_aligned_mask_c;

    assign cacheable_c = !cpu_req_uncached_i && cpu_req_addr_i >= CACHE_START &&
                         cpu_req_addr_i < CACHE_END;
    assign index_c = cpu_req_addr_i[TAG_LSB-1:4];
    assign tag_c   = cpu_req_addr_i[31:TAG_LSB];
    assign word_c  = cpu_req_addr_i[3:2];
    assign hit_c   = cacheable_c && valid_q[index_c] && tag_q[index_c] == tag_c;
    assign store_aligned_data_c = cpu_req_wdata_i << {cpu_req_addr_i[1:0], 3'b000};
    assign store_aligned_mask_c = (cpu_req_wstrb_i << cpu_req_addr_i[1:0]) & 4'hf;
    assign idle_o = state_q == DC_IDLE;

    always_comb begin
        cpu_req_ready_o = 1'b0;
        cpu_resp_valid_o = 1'b0;
        cpu_resp_rdata_o = resp_data_q;
        mem_req_valid_o = 1'b0;
        mem_req_write_o = 1'b0;
        mem_req_addr_o = 32'd0;
        mem_req_wdata_o = 32'd0;
        mem_req_wstrb_o = 4'd0;
        mem_req_uncached_o = 1'b0;
        access_pulse_o = 1'b0;
        miss_pulse_o = 1'b0;

        unique case (state_q)
            DC_IDLE: begin
                if (cpu_req_valid_i) begin
                    if (cpu_req_write_i) begin
                        mem_req_valid_o = 1'b1;
                        mem_req_write_o = 1'b1;
                        mem_req_addr_o = cpu_req_addr_i;
                        mem_req_wdata_o = cpu_req_wdata_i;
                        mem_req_wstrb_o = cpu_req_wstrb_i;
                        mem_req_uncached_o = !cacheable_c;
                        cpu_req_ready_o = mem_req_ready_i;
                        access_pulse_o = cacheable_c && mem_req_ready_i;
                    end else begin
                        cpu_req_ready_o = 1'b1;
                        access_pulse_o = cacheable_c;
                        miss_pulse_o = cacheable_c && !hit_c;
                        if (!cacheable_c) begin
                            mem_req_valid_o = 1'b1;
                            mem_req_write_o = 1'b0;
                            mem_req_addr_o = {cpu_req_addr_i[31:2], 2'b00};
                            mem_req_uncached_o = 1'b1;
                            cpu_req_ready_o = mem_req_ready_i;
                        end
                    end
                end
            end
            DC_RESP: begin
                cpu_resp_valid_o = !killed_q;
                cpu_resp_rdata_o = resp_data_q;
            end
            DC_REFILL_REQ: begin
                mem_req_valid_o = 1'b1;
                mem_req_write_o = 1'b0;
                mem_req_addr_o = {req_addr_q[31:4], 4'b0000} + {28'd0, fill_word_q, 2'b00};
                mem_req_uncached_o = 1'b0;
            end
            default: begin end
        endcase
    end

    integer lane;
    always_ff @(posedge clk) begin
        if (rst) begin
            state_q <= DC_IDLE;
            valid_q <= '0;
            req_addr_q <= '0;
            target_word_q <= '0;
            fill_word_q <= '0;
            resp_data_q <= '0;
            target_data_q <= '0;
            killed_q <= 1'b0;
        end else begin
            if (kill_i && state_q != DC_IDLE) killed_q <= 1'b1;
            unique case (state_q)
                DC_IDLE: begin
                    killed_q <= 1'b0;
                    if (cpu_req_valid_i && cpu_req_write_i && mem_req_ready_i) begin
                        if (hit_c) begin
                            for (lane = 0; lane < 4; lane = lane + 1) begin
                                if (store_aligned_mask_c[lane])
                                    data_q[index_c][word_c][lane*8 +: 8] <=
                                        store_aligned_data_c[lane*8 +: 8];
                            end
                        end
                    end else if (cpu_req_valid_i && !cpu_req_write_i && cpu_req_ready_o) begin
                        req_addr_q <= cpu_req_addr_i;
                        target_word_q <= word_c;
                        if (cacheable_c && hit_c) begin
                            resp_data_q <= data_q[index_c][word_c];
                            state_q <= DC_RESP;
                        end else if (cacheable_c) begin
                            fill_word_q <= 2'd0;
                            target_data_q <= 32'd0;
                            state_q <= DC_REFILL_REQ;
                        end else begin
                            state_q <= DC_UNC_WAIT;
                        end
                    end
                end
                DC_RESP: begin
                    state_q <= DC_IDLE;
                    killed_q <= 1'b0;
                end
                DC_UNC_WAIT: begin
                    if (mem_resp_valid_i) begin
                        if (!killed_q && !kill_i) begin
                            resp_data_q <= mem_resp_rdata_i;
                            state_q <= DC_RESP;
                        end else begin
                            state_q <= DC_IDLE;
                            killed_q <= 1'b0;
                        end
                    end
                end
                DC_REFILL_REQ: begin
                    if (kill_i) begin
                        // If memory accepted the request on the same edge as the
                        // kill, retain ownership until its late response drains.
                        // Otherwise the request was cancelled before acceptance.
                        if (mem_req_ready_i) begin
                            state_q <= DC_REFILL_WAIT;
                            killed_q <= 1'b1;
                        end else begin
                            state_q <= DC_IDLE;
                            killed_q <= 1'b0;
                        end
                    end else if (mem_req_ready_i) begin
                        state_q <= DC_REFILL_WAIT;
                    end
                end
                DC_REFILL_WAIT: begin
                    if (mem_resp_valid_i) begin
                        if (killed_q || kill_i) begin
                            state_q <= DC_IDLE;
                            killed_q <= 1'b0;
                        end else begin
                            data_q[req_addr_q[TAG_LSB-1:4]][fill_word_q] <= mem_resp_rdata_i;
                            if (fill_word_q == target_word_q) target_data_q <= mem_resp_rdata_i;
                            if (fill_word_q == 2'd3) begin
                                valid_q[req_addr_q[TAG_LSB-1:4]] <= 1'b1;
                                tag_q[req_addr_q[TAG_LSB-1:4]] <= req_addr_q[31:TAG_LSB];
                                resp_data_q <= (target_word_q == fill_word_q) ?
                                               mem_resp_rdata_i : target_data_q;
                                state_q <= DC_RESP;
                            end else begin
                                fill_word_q <= fill_word_q + 1'b1;
                                state_q <= DC_REFILL_REQ;
                            end
                        end
                    end
                end
                default: state_q <= DC_IDLE;
            endcase
        end
    end
endmodule
