`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: fixed_execute
// Generated: 2026-07-13
// Source: 053 architecture
module fixed_execute (
    input  core_types_pkg::exec_req_t exec_i,
    input  logic [core_config_pkg::STORE_ID_W-1:0] store_tail_i,
    output logic completion_valid_o,
    output core_types_pkg::completion_t completion_o,
    output logic branch_resolve_valid_o,
    output logic branch_taken_o,
    output logic [31:0] branch_target_o,
    output logic [31:0] branch_actual_next_o,
    output core_types_pkg::pred_kind_e branch_kind_o,
    output logic load_enqueue_o,
    output logic store_enqueue_o,
    output logic [31:0] mem_addr_o
);
    import core_types_pkg::*;
    logic mem_misaligned;

    always_comb begin
        completion_o = '0;
        completion_valid_o = 1'b0;
        branch_resolve_valid_o = 1'b0;
        branch_taken_o = 1'b0;
        branch_target_o = exec_i.uop.pc + exec_i.uop.imm;
        branch_actual_next_o = exec_i.uop.pc + 32'd4;
        branch_kind_o = PRED_NONE;
        mem_addr_o = exec_i.op1 + exec_i.uop.imm;
        mem_misaligned = 1'b0;
        load_enqueue_o = 1'b0;
        store_enqueue_o = 1'b0;

        if (exec_i.valid) begin
            completion_o.valid = 1'b1;
            completion_o.trans_id = exec_i.trans_id;
            unique case (exec_i.uop.fu)
                FU_ALU: begin
                    unique case (exec_i.uop.alu_op)
                        ALU_ADD: completion_o.result =
                            (exec_i.uop.instr[6:0] == 7'b0010111) ?
                            exec_i.uop.pc + exec_i.uop.imm :
                            exec_i.op1 + (exec_i.uop.uses_rs2 ? exec_i.op2 : exec_i.uop.imm);
                        ALU_SUB: completion_o.result = exec_i.op1 - exec_i.op2;
                        ALU_AND: completion_o.result = exec_i.op1 & (exec_i.uop.uses_rs2 ? exec_i.op2 : exec_i.uop.imm);
                        ALU_OR:  completion_o.result = exec_i.op1 | (exec_i.uop.uses_rs2 ? exec_i.op2 : exec_i.uop.imm);
                        ALU_XOR: completion_o.result = exec_i.op1 ^ (exec_i.uop.uses_rs2 ? exec_i.op2 : exec_i.uop.imm);
                        ALU_SLL: completion_o.result = exec_i.op1 << (exec_i.uop.uses_rs2 ? exec_i.op2[4:0] : exec_i.uop.imm[4:0]);
                        ALU_SRL: completion_o.result = exec_i.op1 >> (exec_i.uop.uses_rs2 ? exec_i.op2[4:0] : exec_i.uop.imm[4:0]);
                        ALU_SRA: completion_o.result = $signed(exec_i.op1) >>> (exec_i.uop.uses_rs2 ? exec_i.op2[4:0] : exec_i.uop.imm[4:0]);
                        ALU_SLT: completion_o.result = {31'd0, $signed(exec_i.op1) < $signed(exec_i.uop.uses_rs2 ? exec_i.op2 : exec_i.uop.imm)};
                        ALU_SLTU: completion_o.result = {31'd0, exec_i.op1 < (exec_i.uop.uses_rs2 ? exec_i.op2 : exec_i.uop.imm)};
                        ALU_COPY_B: completion_o.result = exec_i.uop.imm;
                        default: completion_o.result = 32'd0;
                    endcase
                    completion_valid_o = 1'b1;
                end
                FU_BRANCH: begin
                    branch_resolve_valid_o = 1'b1;
                    if (exec_i.uop.is_jal) begin
                        branch_taken_o = 1'b1;
                        branch_actual_next_o = exec_i.uop.pc + exec_i.uop.imm;
                        branch_target_o = branch_actual_next_o;
                        branch_kind_o = PRED_JUMP;
                    end else if (exec_i.uop.is_jalr) begin
                        branch_taken_o = 1'b1;
                        branch_actual_next_o = (exec_i.op1 + exec_i.uop.imm) & 32'hffff_fffe;
                        branch_target_o = branch_actual_next_o;
                        branch_kind_o = ((exec_i.uop.rs1 == 5'd1 || exec_i.uop.rs1 == 5'd5) &&
                                         exec_i.uop.rd == 0) ? PRED_RETURN : PRED_JUMP;
                    end else begin
                        unique case (exec_i.uop.branch_op)
                            BR_BEQ:  branch_taken_o = exec_i.op1 == exec_i.op2;
                            BR_BNE:  branch_taken_o = exec_i.op1 != exec_i.op2;
                            BR_BLT:  branch_taken_o = $signed(exec_i.op1) < $signed(exec_i.op2);
                            BR_BGE:  branch_taken_o = $signed(exec_i.op1) >= $signed(exec_i.op2);
                            BR_BLTU: branch_taken_o = exec_i.op1 < exec_i.op2;
                            BR_BGEU: branch_taken_o = exec_i.op1 >= exec_i.op2;
                            default: branch_taken_o = 1'b0;
                        endcase
                        branch_actual_next_o = branch_taken_o ? branch_target_o : exec_i.uop.pc + 32'd4;
                        branch_kind_o = PRED_COND;
                    end
                    completion_o.result = exec_i.uop.pc + 32'd4;
                    if (branch_taken_o && branch_actual_next_o[1:0] != 0) begin
                        completion_o.exception_valid = 1'b1;
                        completion_o.exception_cause = 5'd0;
                        completion_o.exception_tval = branch_actual_next_o;
                    end
                    completion_valid_o = 1'b1;
                end
                FU_LOAD, FU_STORE: begin
                    mem_misaligned = ((exec_i.uop.mem_size == MEM_HALF) && mem_addr_o[0]) ||
                                     ((exec_i.uop.mem_size == MEM_WORD) && (mem_addr_o[1:0] != 0));
                    if (mem_misaligned) begin
                        completion_o.exception_valid = 1'b1;
                        completion_o.exception_cause = (exec_i.uop.fu == FU_LOAD) ? 5'd4 : 5'd6;
                        completion_o.exception_tval = mem_addr_o;
                        completion_valid_o = 1'b1;
                    end else if (exec_i.uop.fu == FU_LOAD) begin
                        load_enqueue_o = 1'b1;
                    end else begin
                        store_enqueue_o = 1'b1;
                        completion_o.store_slot_valid = 1'b1;
                        completion_o.store_slot = store_tail_i;
                        completion_valid_o = 1'b1;
                    end
                end
                default: begin end
            endcase
        end
    end
endmodule
