`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: myCPU
// Generated: 2026-07-13
// Source: preserved superScalar SoC/TB/FPGA interface contract
module myCPU (
    input  logic        cpu_rst,
    input  logic        cpu_clk,
    output logic [31:0] irom_addr,
    input  logic [31:0] irom_data,
    output logic        irom_ena,
    output logic        dmem_req_valid,
    input  logic        dmem_req_ready,
    output logic        dmem_req_write,
    output logic [31:0] dmem_req_addr,
    output logic [31:0] dmem_req_wdata,
    output logic [3:0]  dmem_req_wstrb,
    output logic        dmem_req_uncached,
    input  logic        dmem_resp_valid,
    input  logic [31:0] dmem_resp_rdata
`ifdef VERILATOR_TB
    ,
    output logic [63:0] dbg_perf_cycle,
    output logic [63:0] dbg_perf_commit,
    output logic [63:0] dbg_perf_branch,
    output logic [63:0] dbg_perf_branch_miss,
    output logic [63:0] dbg_perf_load,
    output logic [63:0] dbg_perf_store,
    output logic [63:0] dbg_perf_dcache_access,
    output logic [63:0] dbg_perf_dcache_miss,
    output logic [63:0] dbg_perf_stall_front,
    output logic [63:0] dbg_perf_stall_mem,
    output logic [63:0] dbg_perf_stall_muldiv,
    output logic [63:0] dbg_perf_stall_load_use
`endif
);
    logic [63:0] perf_cycle, perf_commit, perf_branch, perf_branch_miss;
    logic [63:0] perf_load, perf_store, perf_dcache_access, perf_dcache_miss;
    logic [63:0] perf_stall_front, perf_stall_mem, perf_stall_muldiv, perf_stall_load_use;

    core_top u_core_top (
        .clk(cpu_clk), .rst(cpu_rst),
        .irom_addr_o(irom_addr), .irom_ena_o(irom_ena), .irom_data_i(irom_data),
        .dmem_req_valid_o(dmem_req_valid), .dmem_req_ready_i(dmem_req_ready),
        .dmem_req_write_o(dmem_req_write), .dmem_req_addr_o(dmem_req_addr),
        .dmem_req_wdata_o(dmem_req_wdata), .dmem_req_wstrb_o(dmem_req_wstrb),
        .dmem_req_uncached_o(dmem_req_uncached), .dmem_resp_valid_i(dmem_resp_valid),
        .dmem_resp_rdata_i(dmem_resp_rdata), .perf_cycle_o(perf_cycle),
        .perf_commit_o(perf_commit), .perf_branch_o(perf_branch),
        .perf_branch_miss_o(perf_branch_miss), .perf_load_o(perf_load),
        .perf_store_o(perf_store), .perf_dcache_access_o(perf_dcache_access),
        .perf_dcache_miss_o(perf_dcache_miss), .perf_stall_front_o(perf_stall_front),
        .perf_stall_mem_o(perf_stall_mem), .perf_stall_muldiv_o(perf_stall_muldiv),
        .perf_stall_load_use_o(perf_stall_load_use)
    );

`ifdef VERILATOR_TB
    assign dbg_perf_cycle = perf_cycle;
    assign dbg_perf_commit = perf_commit;
    assign dbg_perf_branch = perf_branch;
    assign dbg_perf_branch_miss = perf_branch_miss;
    assign dbg_perf_load = perf_load;
    assign dbg_perf_store = perf_store;
    assign dbg_perf_dcache_access = perf_dcache_access;
    assign dbg_perf_dcache_miss = perf_dcache_miss;
    assign dbg_perf_stall_front = perf_stall_front;
    assign dbg_perf_stall_mem = perf_stall_mem;
    assign dbg_perf_stall_muldiv = perf_stall_muldiv;
    assign dbg_perf_stall_load_use = perf_stall_load_use;
`endif
endmodule
