`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: muldiv_unit
// Generated: 2026-07-13
// Source: 053 architecture + MUL_0/DIV_0 framework contract
module muldiv_unit (
    input  logic clk,
    input  logic rst,
    input  logic kill_i,
    input  logic req_valid_i,
    output logic req_ready_o,
    input  logic [core_config_pkg::TRANS_ID_W-1:0] req_trans_id_i,
    input  core_types_pkg::muldiv_op_e req_op_i,
    input  logic [31:0] req_a_i,
    input  logic [31:0] req_b_i,
    output logic resp_valid_o,
    output logic [core_config_pkg::TRANS_ID_W-1:0] resp_trans_id_o,
    output logic [31:0] resp_result_o,
    output logic busy_o
);
    import core_types_pkg::*;
    import core_config_pkg::*;

    logic busy_q, killed_q, is_div_q;
    logic [TRANS_ID_W-1:0] tid_q;
    muldiv_op_e op_q;
    logic [31:0] a_q, b_q;
    logic [2:0] mul_valid_q;
    logic signed [32:0] mul_a, mul_b;
    logic signed [65:0] mul_product;
    logic div_in_valid, div_out_valid;
    logic [63:0] div_raw;
    logic [31:0] abs_a, abs_b;
    logic [31:0] quot_abs, rem_abs, quot_res, rem_res;
    logic raw_done;

    assign req_ready_o = !busy_q;
    assign busy_o = busy_q;
    assign mul_a = (req_op_i == M_MULHU) ? {1'b0, req_a_i} : {req_a_i[31], req_a_i};
    assign mul_b = ((req_op_i == M_MUL) || (req_op_i == M_MULH)) ?
                   {req_b_i[31], req_b_i} : {1'b0, req_b_i};
    assign abs_a = req_a_i[31] ? (~req_a_i + 1'b1) : req_a_i;
    assign abs_b = req_b_i[31] ? (~req_b_i + 1'b1) : req_b_i;
    assign div_in_valid = req_valid_i && req_ready_o && req_op_i[2];

    MUL_0 u_mul (
        .CLK(clk), .A(mul_a), .B(mul_b), .P(mul_product)
    );

    DIV_0 u_div (
        .aclk(clk),
        .s_axis_dividend_tvalid(div_in_valid),
        .s_axis_dividend_tready(),
        .s_axis_dividend_tdata((req_op_i == M_DIV || req_op_i == M_REM) ? abs_a : req_a_i),
        .s_axis_divisor_tvalid(div_in_valid),
        .s_axis_divisor_tready(),
        .s_axis_divisor_tdata((req_op_i == M_DIV || req_op_i == M_REM) ? abs_b : req_b_i),
        .m_axis_dout_tvalid(div_out_valid),
        .m_axis_dout_tdata(div_raw)
    );

    assign quot_abs = div_raw[63:32];
    assign rem_abs  = div_raw[31:0];

    always_comb begin
        if (b_q == 32'd0) begin
            quot_res = 32'hffff_ffff;
            rem_res = a_q;
        end else if ((op_q == M_DIV || op_q == M_REM) &&
                     a_q == 32'h8000_0000 && b_q == 32'hffff_ffff) begin
            quot_res = 32'h8000_0000;
            rem_res = 32'd0;
        end else if (op_q == M_DIV || op_q == M_REM) begin
            quot_res = (a_q[31] ^ b_q[31]) ? (~quot_abs + 1'b1) : quot_abs;
            rem_res = a_q[31] ? (~rem_abs + 1'b1) : rem_abs;
        end else begin
            quot_res = quot_abs;
            rem_res = rem_abs;
        end

        unique case (op_q)
            M_MUL:    resp_result_o = mul_product[31:0];
            M_MULH,
            M_MULHSU,
            M_MULHU:  resp_result_o = mul_product[63:32];
            M_DIV,
            M_DIVU:   resp_result_o = quot_res;
            M_REM,
            M_REMU:   resp_result_o = rem_res;
            default:  resp_result_o = 32'd0;
        endcase
    end

    assign raw_done = is_div_q ? div_out_valid : mul_valid_q[2];
    assign resp_valid_o = raw_done && busy_q && !killed_q;
    assign resp_trans_id_o = tid_q;

    always_ff @(posedge clk) begin
        if (rst) begin
            busy_q <= 1'b0;
            killed_q <= 1'b0;
            is_div_q <= 1'b0;
            tid_q <= '0;
            op_q <= M_MUL;
            a_q <= '0;
            b_q <= '0;
            mul_valid_q <= '0;
        end else begin
            mul_valid_q <= {mul_valid_q[1:0],
                            req_valid_i && req_ready_o && !req_op_i[2]};
            if (req_valid_i && req_ready_o) begin
                busy_q <= 1'b1;
                killed_q <= 1'b0;
                is_div_q <= req_op_i[2];
                tid_q <= req_trans_id_i;
                op_q <= req_op_i;
                a_q <= req_a_i;
                b_q <= req_b_i;
            end
            if (kill_i && busy_q) killed_q <= 1'b1;
            if (raw_done && busy_q) begin
                busy_q <= 1'b0;
                killed_q <= 1'b0;
            end
        end
    end
endmodule
