`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: core_config_pkg
// Generated: 2026-07-13
// Source: 053_superscalar_framework_inorder_single_issue_core_architecture.md
package core_config_pkg;
    localparam int unsigned XLEN               = 32;
    localparam logic [31:0] RESET_PC           = 32'h8000_0000;
    localparam int unsigned FETCH_QUEUE_DEPTH  = 4;
    localparam int unsigned SCOREBOARD_DEPTH   = 8;
    localparam int unsigned STORE_BUFFER_DEPTH = 4;
    localparam int unsigned LOAD_QUEUE_DEPTH   = 2;
    localparam int unsigned BTB_ENTRIES        = 64;
    localparam int unsigned RAS_DEPTH          = 8;
    localparam int unsigned DCACHE_LINES       = 512;
    localparam int unsigned DCACHE_LINE_BYTES  = 16;
    localparam logic [31:0] DRAM_START          = 32'h8010_0000;
    localparam logic [31:0] DRAM_END            = 32'h8014_0000;
    localparam int unsigned TRANS_ID_W          = $clog2(SCOREBOARD_DEPTH);
    localparam int unsigned STORE_ID_W          = $clog2(STORE_BUFFER_DEPTH);
endpackage
