`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: core_top
// Generated: 2026-07-13
// Source: 053 architecture + 054 implementation plan
module core_top (
    input  logic clk,
    input  logic rst,
    output logic [31:0] irom_addr_o,
    output logic irom_ena_o,
    input  logic [31:0] irom_data_i,
    output logic dmem_req_valid_o,
    input  logic dmem_req_ready_i,
    output logic dmem_req_write_o,
    output logic [31:0] dmem_req_addr_o,
    output logic [31:0] dmem_req_wdata_o,
    output logic [3:0] dmem_req_wstrb_o,
    output logic dmem_req_uncached_o,
    input  logic dmem_resp_valid_i,
    input  logic [31:0] dmem_resp_rdata_i,
    output logic [63:0] perf_cycle_o,
    output logic [63:0] perf_commit_o,
    output logic [63:0] perf_branch_o,
    output logic [63:0] perf_branch_miss_o,
    output logic [63:0] perf_load_o,
    output logic [63:0] perf_store_o,
    output logic [63:0] perf_dcache_access_o,
    output logic [63:0] perf_dcache_miss_o,
    output logic [63:0] perf_stall_front_o,
    output logic [63:0] perf_stall_mem_o,
    output logic [63:0] perf_stall_muldiv_o,
    output logic [63:0] perf_stall_load_use_o
);
    import core_config_pkg::*;
    import core_types_pkg::*;

    localparam int unsigned SB_CNT_W = $clog2(SCOREBOARD_DEPTH + 1);
    localparam int unsigned ST_CNT_W = $clog2(STORE_BUFFER_DEPTH + 1);
    localparam int unsigned LD_CNT_W = $clog2(LOAD_QUEUE_DEPTH + 1);

    logic id_valid_q;
    uop_t id_uop_q, decoded_uop;
    fetch_entry_t fetch_head_entry;
    logic fetch_valid, fetch_pop;

    logic [31:0] rf_rs1_data, rf_rs2_data, rf_write_data;
    logic rf_write_valid;
    logic wb_valid_q;
    logic [4:0] wb_rd_q;
    logic [31:0] wb_data_q;
    scoreboard_entry_t scoreboard_q [0:SCOREBOARD_DEPTH-1];
    // Architectural-register -> youngest in-flight producer.  A direct map
    // replaces the backwards scoreboard CAM walk on every decode cycle.
    logic [31:0] producer_valid_q;
    logic [TRANS_ID_W-1:0] producer_tid_q [0:31];
    logic [TRANS_ID_W-1:0] issue_ptr_q, commit_ptr_q;
    logic [SB_CNT_W-1:0] scoreboard_count_q;
    logic serial_pending_q;

    exec_req_t exec_q;
    completion_t fixed_completion;
    logic fixed_completion_valid;
    logic branch_resolve_valid_c, branch_taken_c, branch_miss_c;
    logic [31:0] branch_target_c, branch_actual_next_c;
    pred_kind_e branch_kind_c;
    logic branch_resolve_valid, branch_taken, branch_miss;
    logic branch_predictor_update_valid_q;
    logic [31:0] branch_target, branch_actual_next, branch_pc_q;
    pred_kind_e branch_kind;

    store_entry_t store_q [0:STORE_BUFFER_DEPTH-1];
    logic [STORE_BUFFER_DEPTH-1:0] store_committed_q;
    logic [STORE_ID_W-1:0] store_head_q, store_tail_q;
    logic [ST_CNT_W-1:0] store_count_q;
    logic [7:0] next_store_seq_q;
    load_entry_t load_q [0:LOAD_QUEUE_DEPTH-1];
    logic [$clog2(LOAD_QUEUE_DEPTH)-1:0] load_head_q, load_tail_q;
    logic [LD_CNT_W-1:0] load_count_q;
    logic load_active_q;
    load_entry_t load_active_meta_q;

    logic [31:0] src1_value, src2_value;
    logic src1_ready, src2_ready, src1_found, src2_found;
    logic [TRANS_ID_W-1:0] src1_tid, src2_tid;
    logic issue_fu_ready, issue_fire;
    logic exec_load_enqueue, exec_store_enqueue;
    logic [31:0] exec_mem_addr_calc, exec_mem_addr_q;

    logic dc_req_valid, dc_req_ready, dc_req_write, dc_req_uncached;
    logic [31:0] dc_req_addr, dc_req_wdata;
    logic [3:0] dc_req_wstrb;
    logic dc_resp_valid, dc_idle, dc_access_pulse, dc_miss_pulse;
    logic [31:0] dc_resp_rdata;
    logic dc_mem_req_valid, dc_mem_req_ready, dc_mem_req_write, dc_mem_req_uncached;
    logic [31:0] dc_mem_req_addr, dc_mem_req_wdata;
    logic [3:0] dc_mem_req_wstrb;
    logic dc_mem_resp_valid;
    logic [31:0] dc_mem_resp_rdata;
    logic store_drain_fire, load_start_fire;
    logic older_store_pending;
    logic [31:0] load_shifted, load_result, load_merged_word;
    logic [31:0] load_forward_data_c, store_shifted_data_c;
    logic [31:0] load_forward_byte_mask_c;
    logic [3:0] load_forward_mask_c, store_shifted_mask_c;
    logic load_completion_valid, load_forward_complete, load_pop_fire;
    logic load_direct_candidate, load_direct_start_fire, load_queue_start_fire;
    logic load_enqueue_fire, direct_older_store_pending;
    logic [3:0] load_needed_mask;
    load_entry_t load_completion_meta, load_direct_meta;

    logic mdu_req_valid, mdu_req_ready, mdu_resp_valid, mdu_busy;
    logic [TRANS_ID_W-1:0] mdu_resp_tid;
    logic [31:0] mdu_resp_result;

    scoreboard_entry_t commit_entry;
    logic commit_ready, commit_fire, commit_normal;
    logic commit_store_mark;
    logic full_flush, redirect_valid;
    logic [31:0] redirect_target;
    logic mem_quiescent;

    logic [11:0] csr_read_addr, csr_write_addr;
    logic [31:0] csr_read_data, csr_write_data, csr_result;
    logic csr_write_valid, csr_trap_valid, csr_mret_valid;
    logic [31:0] csr_mtvec, csr_mepc;

    logic predictor_update_valid, predictor_commit_call, predictor_commit_return;
    logic [31:0] predictor_update_target;

    logic [63:0] cycle_q, commit_count_q, branch_count_q, branch_miss_count_q;
    logic [63:0] load_count_perf_q, store_count_perf_q;
    logic [63:0] dcache_access_q, dcache_miss_q;
    logic [63:0] stall_front_q, stall_mem_q, stall_muldiv_q, stall_load_use_q;
    logic stall_front_c, stall_mem_c, stall_muldiv_c, stall_raw_c;

    integer i;
    integer mem_i;
    integer fwd_i;
    integer fwd_idx;
    integer fwd_lane;
    integer merge_lane;
    integer committed_tmp;

    function automatic logic store_is_older(
        input logic [7:0] cutoff,
        input logic [7:0] seq_value
    );
        logic [7:0] delta;
        begin
            delta = cutoff - seq_value;
            store_is_older = (delta != 0) && !delta[7];
        end
    endfunction

    function automatic logic [3:0] load_byte_mask(
        input mem_size_e size,
        input logic [1:0] byte_offset
    );
        begin
            unique case (size)
                MEM_BYTE: load_byte_mask = 4'b0001 << byte_offset;
                MEM_HALF: load_byte_mask = 4'b0011 << byte_offset;
                default:  load_byte_mask = 4'b1111;
            endcase
        end
    endfunction

    function automatic logic addr_is_dram(input logic [31:0] addr);
        begin
            // DRAM is a naturally aligned 256 KiB window at 0x8010_0000.
            addr_is_dram = addr[31:18] == DRAM_START[31:18];
        end
    endfunction

    assign perf_cycle_o = cycle_q;
    assign perf_commit_o = commit_count_q;
    assign perf_branch_o = branch_count_q;
    assign perf_branch_miss_o = branch_miss_count_q;
    assign perf_load_o = load_count_perf_q;
    assign perf_store_o = store_count_perf_q;
    assign perf_dcache_access_o = dcache_access_q;
    assign perf_dcache_miss_o = dcache_miss_q;
    assign perf_stall_front_o = stall_front_q;
    assign perf_stall_mem_o = stall_mem_q;
    assign perf_stall_muldiv_o = stall_muldiv_q;
    assign perf_stall_load_use_o = stall_load_use_q;

    assign stall_raw_c = id_valid_q && ((!src1_ready && src1_found) ||
                                        (!src2_ready && src2_found));
    assign stall_mem_c = id_valid_q &&
                         (id_uop_q.fu == FU_LOAD || id_uop_q.fu == FU_STORE) && !issue_fire;
    assign stall_muldiv_c = id_valid_q && id_uop_q.fu == FU_MULDIV && !issue_fire;
    assign stall_front_c = !id_valid_q && scoreboard_count_q < SB_CNT_W'(SCOREBOARD_DEPTH);

    perf_counters u_perf_counters (
        .clk(clk), .rst(rst), .commit_i(commit_normal),
        .commit_load_i(commit_normal && commit_entry.fu == FU_LOAD),
        .commit_store_i(commit_normal && commit_entry.fu == FU_STORE),
        .branch_i(branch_resolve_valid), .branch_miss_i(branch_miss),
        .dcache_access_i(dc_access_pulse), .dcache_miss_i(dc_miss_pulse),
        .stall_front_i(stall_front_c), .stall_mem_i(stall_mem_c),
        .stall_muldiv_i(stall_muldiv_c), .stall_raw_i(stall_raw_c),
        .cycle_o(cycle_q), .commit_o(commit_count_q), .branch_o(branch_count_q),
        .branch_miss_o(branch_miss_count_q), .load_o(load_count_perf_q),
        .store_o(store_count_perf_q), .dcache_access_o(dcache_access_q),
        .dcache_miss_o(dcache_miss_q), .stall_front_o(stall_front_q),
        .stall_mem_o(stall_mem_q), .stall_muldiv_o(stall_muldiv_q),
        .stall_raw_o(stall_load_use_q)
    );

    assign fetch_pop = fetch_valid && (!id_valid_q || issue_fire) && !redirect_valid;

    frontend u_frontend (
        .clk(clk), .rst(rst), .redirect_valid_i(redirect_valid),
        .redirect_target_i(redirect_target), .irom_addr_o(irom_addr_o),
        .irom_ena_o(irom_ena_o), .irom_data_i(irom_data_i),
        .fetch_valid_o(fetch_valid), .fetch_entry_o(fetch_head_entry),
        .fetch_ready_i(fetch_pop), .predictor_update_valid_i(predictor_update_valid),
        .predictor_update_pc_i(branch_pc_q), .predictor_update_taken_i(branch_taken),
        .predictor_update_target_i(predictor_update_target),
        .predictor_update_kind_i(branch_kind),
        .predictor_commit_call_i(predictor_commit_call),
        .predictor_commit_return_i(predictor_commit_return),
        .predictor_commit_link_i(commit_entry.link_addr)
    );

    decoder u_decoder (.fetch_i(fetch_head_entry), .uop_o(decoded_uop));

    assign rf_write_valid = wb_valid_q;
    assign rf_write_data = wb_data_q;
    regfile u_regfile (
        .clk(clk), .rst(rst), .rs1_addr_i(id_uop_q.rs1), .rs2_addr_i(id_uop_q.rs2),
        .rs1_data_o(rf_rs1_data), .rs2_data_o(rf_rs2_data),
        .write_valid_i(rf_write_valid), .write_addr_i(wb_rd_q),
        .write_data_i(rf_write_data)
    );

    always_ff @(posedge clk) begin
        if (rst) begin
            id_valid_q <= 1'b0;
            id_uop_q <= '0;
        end else if (redirect_valid) begin
            id_valid_q <= 1'b0;
        end else begin
            if (fetch_pop) begin
                id_uop_q <= decoded_uop;
                id_valid_q <= 1'b1;
            end else if (issue_fire) begin
                id_valid_q <= 1'b0;
            end
        end
    end

    always_comb begin
        src1_value = rf_rs1_data;
        src2_value = rf_rs2_data;
        if (id_uop_q.rs1 == 0) src1_value = 32'd0;
        if (id_uop_q.rs2 == 0) src2_value = 32'd0;
        // Architectural RF write is pipelined by one cycle to remove the
        // circular-scoreboard head mux from the RF write-data/fanout path.
        // This bypass covers the single cycle before the RF array is updated.
        if (wb_valid_q && id_uop_q.rs1 == wb_rd_q && id_uop_q.rs1 != 0)
            src1_value = wb_data_q;
        if (wb_valid_q && id_uop_q.rs2 == wb_rd_q && id_uop_q.rs2 != 0)
            src2_value = wb_data_q;
        src1_ready = 1'b1;
        src2_ready = 1'b1;
        src1_found = 1'b0;
        src2_found = 1'b0;
        src1_tid = '0;
        src2_tid = '0;
        if (id_uop_q.uses_rs1 && id_uop_q.rs1 != 0 &&
            producer_valid_q[id_uop_q.rs1]) begin
            src1_found = 1'b1;
            src1_tid = producer_tid_q[id_uop_q.rs1];
            src1_ready = scoreboard_q[producer_tid_q[id_uop_q.rs1]].done;
            src1_value = scoreboard_q[producer_tid_q[id_uop_q.rs1]].result;
        end
        if (id_uop_q.uses_rs2 && id_uop_q.rs2 != 0 &&
            producer_valid_q[id_uop_q.rs2]) begin
            src2_found = 1'b1;
            src2_tid = producer_tid_q[id_uop_q.rs2];
            src2_ready = scoreboard_q[producer_tid_q[id_uop_q.rs2]].done;
            src2_value = scoreboard_q[producer_tid_q[id_uop_q.rs2]].result;
        end
        if (src1_found) begin
            if (fixed_completion_valid && fixed_completion.trans_id == src1_tid) begin
                src1_ready = 1'b1; src1_value = fixed_completion.result;
            end else if (load_completion_valid && load_completion_meta.trans_id == src1_tid) begin
                src1_ready = 1'b1; src1_value = load_result;
            end else if (mdu_resp_valid && mdu_resp_tid == src1_tid) begin
                src1_ready = 1'b1; src1_value = mdu_resp_result;
            end
        end
        if (src2_found) begin
            if (fixed_completion_valid && fixed_completion.trans_id == src2_tid) begin
                src2_ready = 1'b1; src2_value = fixed_completion.result;
            end else if (load_completion_valid && load_completion_meta.trans_id == src2_tid) begin
                src2_ready = 1'b1; src2_value = load_result;
            end else if (mdu_resp_valid && mdu_resp_tid == src2_tid) begin
                src2_ready = 1'b1; src2_value = mdu_resp_result;
            end
        end
    end

    always_comb begin
        issue_fu_ready = 1'b1;
        unique case (id_uop_q.fu)
            FU_LOAD: issue_fu_ready = (load_count_q + LD_CNT_W'(exec_q.valid && exec_q.uop.fu == FU_LOAD)) < LD_CNT_W'(LOAD_QUEUE_DEPTH);
            FU_STORE: issue_fu_ready = (store_count_q + ST_CNT_W'(exec_q.valid && exec_q.uop.fu == FU_STORE)) < ST_CNT_W'(STORE_BUFFER_DEPTH);
            FU_MULDIV: issue_fu_ready = mdu_req_ready && !(exec_q.valid && exec_q.uop.fu == FU_MULDIV);
            default: issue_fu_ready = 1'b1;
        endcase
        if (id_uop_q.serialize) issue_fu_ready = issue_fu_ready &&
                                               (scoreboard_count_q == 0) && !serial_pending_q;
        else issue_fu_ready = issue_fu_ready && !serial_pending_q;
    end

    // A full window may still allocate when its done head commits this cycle.
    // issue_ptr == commit_ptr in that case; textual NBA priority makes the new
    // allocation win after the old head is cleared.
    assign issue_fire = id_valid_q && src1_ready && src2_ready && issue_fu_ready &&
                        ((scoreboard_count_q < SB_CNT_W'(SCOREBOARD_DEPTH)) || commit_fire) &&
                        !branch_resolve_valid_c && !redirect_valid;

    fixed_execute u_fixed_execute (
        .exec_i(exec_q), .store_tail_i(store_tail_q),
        .completion_valid_o(fixed_completion_valid), .completion_o(fixed_completion),
        .branch_resolve_valid_o(branch_resolve_valid_c), .branch_taken_o(branch_taken_c),
        .branch_target_o(branch_target_c), .branch_actual_next_o(branch_actual_next_c),
        .branch_kind_o(branch_kind_c), .load_enqueue_o(exec_load_enqueue),
        .store_enqueue_o(exec_store_enqueue), .mem_addr_o(exec_mem_addr_calc)
    );

    assign branch_miss_c = branch_resolve_valid_c && !fixed_completion.exception_valid &&
                           (branch_actual_next_c != exec_q.uop.pred_next_pc);
    assign predictor_update_valid = branch_predictor_update_valid_q;
    assign predictor_update_target = branch_target;

    // Snapshot all currently older stores when a load leaves EX. Store entries
    // are walked in program order so a younger overlapping store wins per byte.
    always_comb begin
        load_forward_mask_c = 4'd0;
        load_forward_data_c = 32'd0;
        store_shifted_mask_c = 4'd0;
        store_shifted_data_c = 32'd0;
        fwd_idx = 0;
        if (exec_load_enqueue && addr_is_dram(exec_mem_addr_q)) begin
            for (fwd_i = 0; fwd_i < STORE_BUFFER_DEPTH; fwd_i = fwd_i + 1) begin
                fwd_idx = (int'(store_head_q) + fwd_i) % STORE_BUFFER_DEPTH;
                if (fwd_i < int'(store_count_q) && store_q[fwd_idx].valid &&
                    store_q[fwd_idx].addr[31:2] == exec_mem_addr_q[31:2]) begin
                    store_shifted_mask_c = (store_q[fwd_idx].wstrb << store_q[fwd_idx].addr[1:0]) & 4'hf;
                    store_shifted_data_c = store_q[fwd_idx].wdata << {store_q[fwd_idx].addr[1:0], 3'b000};
                    for (fwd_lane = 0; fwd_lane < 4; fwd_lane = fwd_lane + 1) begin
                        if (store_shifted_mask_c[fwd_lane]) begin
                            load_forward_mask_c[fwd_lane] = 1'b1;
                            load_forward_data_c[fwd_lane*8 +: 8] =
                                store_shifted_data_c[fwd_lane*8 +: 8];
                        end
                    end
                end
            end
        end
    end

    muldiv_unit u_muldiv (
        .clk(clk), .rst(rst), .kill_i(full_flush),
        .req_valid_i(mdu_req_valid), .req_ready_o(mdu_req_ready),
        .req_trans_id_i(exec_q.trans_id), .req_op_i(exec_q.uop.muldiv_op),
        .req_a_i(exec_q.op1), .req_b_i(exec_q.op2),
        .resp_valid_o(mdu_resp_valid), .resp_trans_id_o(mdu_resp_tid),
        .resp_result_o(mdu_resp_result), .busy_o(mdu_busy)
    );
    assign mdu_req_valid = exec_q.valid && exec_q.uop.fu == FU_MULDIV && !full_flush;

    always_comb begin
        older_store_pending = 1'b0;
        direct_older_store_pending = 1'b0;
        dc_req_valid = 1'b0;
        dc_req_write = 1'b0;
        dc_req_addr = 32'd0;
        dc_req_wdata = 32'd0;
        dc_req_wstrb = 4'd0;
        dc_req_uncached = 1'b0;
        if (load_count_q != 0) begin
            for (mem_i = 0; mem_i < STORE_BUFFER_DEPTH; mem_i = mem_i + 1) begin
                if (store_q[mem_i].valid &&
                    store_is_older(load_q[load_head_q].store_seq_cutoff,
                                   store_q[mem_i].store_seq)) older_store_pending = 1'b1;
            end
        end
        if (exec_load_enqueue) begin
            for (mem_i = 0; mem_i < STORE_BUFFER_DEPTH; mem_i = mem_i + 1) begin
                if (store_q[mem_i].valid &&
                    store_is_older(next_store_seq_q, store_q[mem_i].store_seq))
                    direct_older_store_pending = 1'b1;
            end
        end
        load_direct_candidate = !full_flush && exec_load_enqueue &&
                                (!load_active_q || dc_resp_valid) && load_count_q == 0 &&
                                (addr_is_dram(exec_mem_addr_q) ||
                                 (!direct_older_store_pending &&
                                  exec_q.trans_id == commit_ptr_q));
        if (store_count_q != 0 && store_q[store_head_q].valid &&
            store_committed_q[store_head_q]) begin
            dc_req_valid = 1'b1;
            dc_req_write = 1'b1;
            dc_req_addr = store_q[store_head_q].addr;
            dc_req_wdata = store_q[store_head_q].wdata;
            dc_req_wstrb = store_q[store_head_q].wstrb;
            dc_req_uncached = store_q[store_head_q].uncached;
        end else if (load_direct_candidate) begin
            dc_req_valid = 1'b1;
            dc_req_write = 1'b0;
            dc_req_addr = exec_mem_addr_q;
            dc_req_uncached = !addr_is_dram(exec_mem_addr_q);
        end else if (!full_flush && (!load_active_q || dc_resp_valid) &&
                     load_count_q != 0 && !load_forward_complete &&
                     (addr_is_dram(load_q[load_head_q].addr) ||
                      (!older_store_pending &&
                       load_q[load_head_q].trans_id == commit_ptr_q))) begin
            dc_req_valid = 1'b1;
            dc_req_write = 1'b0;
            dc_req_addr = load_q[load_head_q].addr;
            dc_req_uncached = !addr_is_dram(load_q[load_head_q].addr);
        end
    end

    assign load_needed_mask = load_byte_mask(load_q[load_head_q].size,
                                             load_q[load_head_q].addr[1:0]);
    assign load_forward_complete = !load_active_q && load_count_q != 0 &&
                                   addr_is_dram(load_q[load_head_q].addr) &&
                                   ((load_q[load_head_q].forward_mask & load_needed_mask) == load_needed_mask);
    assign store_drain_fire = dc_req_valid && dc_req_write && dc_req_ready;
    assign load_start_fire = dc_req_valid && !dc_req_write && dc_req_ready;
    assign load_direct_start_fire = load_start_fire && load_direct_candidate;
    assign load_queue_start_fire = load_start_fire && !load_direct_candidate;
    assign load_pop_fire = load_queue_start_fire || load_forward_complete;
    assign load_enqueue_fire = exec_load_enqueue && !load_direct_start_fire;
    always_comb begin
        load_direct_meta = '0;
        load_direct_meta.valid = 1'b1;
        load_direct_meta.trans_id = exec_q.trans_id;
        load_direct_meta.addr = exec_mem_addr_q;
        load_direct_meta.size = exec_q.uop.mem_size;
        load_direct_meta.load_unsigned = exec_q.uop.load_unsigned;
        load_direct_meta.store_seq_cutoff = next_store_seq_q;
        load_direct_meta.forward_mask = load_forward_mask_c;
        load_direct_meta.forward_data = load_forward_data_c;
        load_completion_meta = load_forward_complete ? load_q[load_head_q] : load_active_meta_q;
        load_forward_byte_mask_c = 32'd0;
        for (merge_lane = 0; merge_lane < 4; merge_lane = merge_lane + 1)
            load_forward_byte_mask_c[merge_lane*8 +: 8] = {8{load_completion_meta.forward_mask[merge_lane]}};
        load_merged_word = load_forward_complete ? load_completion_meta.forward_data :
                           ((dc_resp_rdata & ~load_forward_byte_mask_c) |
                            (load_completion_meta.forward_data & load_forward_byte_mask_c));
        load_shifted = load_merged_word >> {load_completion_meta.addr[1:0], 3'b000};
        unique case (load_completion_meta.size)
            MEM_BYTE: load_result = load_completion_meta.load_unsigned ?
                                    {24'd0, load_shifted[7:0]} : {{24{load_shifted[7]}}, load_shifted[7:0]};
            MEM_HALF: load_result = load_completion_meta.load_unsigned ?
                                    {16'd0, load_shifted[15:0]} : {{16{load_shifted[15]}}, load_shifted[15:0]};
            default: load_result = load_shifted;
        endcase
    end
    assign load_completion_valid = (dc_resp_valid && load_active_q) || load_forward_complete;

    dcache u_dcache (
        .clk(clk), .rst(rst), .kill_i(full_flush),
        .cpu_req_valid_i(dc_req_valid), .cpu_req_ready_o(dc_req_ready),
        .cpu_req_write_i(dc_req_write), .cpu_req_addr_i(dc_req_addr),
        .cpu_req_wdata_i(dc_req_wdata), .cpu_req_wstrb_i(dc_req_wstrb),
        .cpu_req_uncached_i(dc_req_uncached), .cpu_resp_valid_o(dc_resp_valid),
        .cpu_resp_rdata_o(dc_resp_rdata), .mem_req_valid_o(dc_mem_req_valid),
        .mem_req_ready_i(dc_mem_req_ready), .mem_req_write_o(dc_mem_req_write),
        .mem_req_addr_o(dc_mem_req_addr), .mem_req_wdata_o(dc_mem_req_wdata),
        .mem_req_wstrb_o(dc_mem_req_wstrb), .mem_req_uncached_o(dc_mem_req_uncached),
        .mem_resp_valid_i(dc_mem_resp_valid), .mem_resp_rdata_i(dc_mem_resp_rdata),
        .access_pulse_o(dc_access_pulse), .miss_pulse_o(dc_miss_pulse), .idle_o(dc_idle)
    );

    dmem_regslice u_dmem_regslice (
        .clk(clk), .rst(rst),
        .s_req_valid_i(dc_mem_req_valid), .s_req_ready_o(dc_mem_req_ready),
        .s_req_write_i(dc_mem_req_write), .s_req_addr_i(dc_mem_req_addr),
        .s_req_wdata_i(dc_mem_req_wdata), .s_req_wstrb_i(dc_mem_req_wstrb),
        .s_req_uncached_i(dc_mem_req_uncached),
        .s_resp_valid_o(dc_mem_resp_valid), .s_resp_rdata_o(dc_mem_resp_rdata),
        .m_req_valid_o(dmem_req_valid_o), .m_req_ready_i(dmem_req_ready_i),
        .m_req_write_o(dmem_req_write_o), .m_req_addr_o(dmem_req_addr_o),
        .m_req_wdata_o(dmem_req_wdata_o), .m_req_wstrb_o(dmem_req_wstrb_o),
        .m_req_uncached_o(dmem_req_uncached_o),
        .m_resp_valid_i(dmem_resp_valid_i), .m_resp_rdata_i(dmem_resp_rdata_i)
    );

    assign commit_entry = scoreboard_q[commit_ptr_q];
    assign mem_quiescent = (store_count_q == 0) && (load_count_q == 0) &&
                           !load_active_q && dc_idle && !mdu_busy;
    always_comb begin
        commit_ready = commit_entry.occupied && commit_entry.done;
        if (commit_entry.fu == FU_STORE && commit_entry.store_slot_valid)
            commit_ready = commit_ready && store_q[commit_entry.store_slot].valid;
        if (commit_entry.sys_op == SYS_FENCE || commit_entry.sys_op == SYS_FENCE_I)
            commit_ready = commit_ready && mem_quiescent;
    end
    assign commit_fire = commit_ready;
    assign commit_normal = commit_fire && !commit_entry.exception_valid;
    assign commit_store_mark = commit_normal && commit_entry.fu == FU_STORE && commit_entry.store_slot_valid;
    recovery_ctrl u_recovery_ctrl (
        .commit_fire_i(commit_fire), .commit_entry_i(commit_entry),
        .mtvec_i(csr_mtvec), .mepc_i(csr_mepc), .branch_miss_i(branch_miss),
        .branch_actual_next_i(branch_actual_next), .full_flush_o(full_flush),
        .redirect_valid_o(redirect_valid), .redirect_target_o(redirect_target)
    );

    assign csr_read_addr = commit_entry.csr_addr;
    always_comb begin
        unique case (commit_entry.csr_op)
            CSR_WRITE: csr_write_data = commit_entry.csr_src;
            CSR_SET: csr_write_data = csr_read_data | commit_entry.csr_src;
            CSR_CLEAR: csr_write_data = csr_read_data & ~commit_entry.csr_src;
            default: csr_write_data = csr_read_data;
        endcase
        csr_result = csr_read_data;
    end
    assign csr_write_valid = commit_normal && commit_entry.sys_op == SYS_CSR &&
                             (commit_entry.csr_op == CSR_WRITE || commit_entry.csr_src != 0);
    assign csr_write_addr = commit_entry.csr_addr;
    assign csr_trap_valid = commit_fire && commit_entry.exception_valid;
    assign csr_mret_valid = commit_normal && commit_entry.sys_op == SYS_MRET;

    csr_file u_csr (
        .clk(clk), .rst(rst), .read_addr_i(csr_read_addr), .read_data_o(csr_read_data),
        .write_valid_i(csr_write_valid), .write_addr_i(csr_write_addr),
        .write_data_i(csr_write_data), .trap_valid_i(csr_trap_valid),
        .trap_pc_i(commit_entry.pc), .trap_cause_i(commit_entry.exception_cause),
        .trap_tval_i(commit_entry.exception_tval), .mret_valid_i(csr_mret_valid),
        .cycle_i(cycle_q), .instret_i(commit_count_q), .mtvec_o(csr_mtvec), .mepc_o(csr_mepc)
    );

    assign predictor_commit_call = commit_normal && commit_entry.is_call;
    assign predictor_commit_return = commit_normal && commit_entry.is_return;

    always_ff @(posedge clk) begin
        if (rst) begin
            issue_ptr_q <= '0;
            commit_ptr_q <= '0;
            scoreboard_count_q <= '0;
            producer_valid_q <= '0;
            wb_valid_q <= 1'b0;
            wb_rd_q <= '0;
            wb_data_q <= '0;
            serial_pending_q <= 1'b0;
            exec_q <= '0;
            exec_mem_addr_q <= '0;
            branch_resolve_valid <= 1'b0;
            branch_predictor_update_valid_q <= 1'b0;
            branch_taken <= 1'b0;
            branch_miss <= 1'b0;
            branch_target <= '0;
            branch_actual_next <= '0;
            branch_pc_q <= '0;
            branch_kind <= PRED_NONE;
            store_head_q <= '0;
            store_tail_q <= '0;
            store_count_q <= '0;
            store_committed_q <= '0;
            next_store_seq_q <= '0;
            load_head_q <= '0;
            load_tail_q <= '0;
            load_count_q <= '0;
            load_active_q <= 1'b0;
            load_active_meta_q <= '0;
            for (i = 0; i < SCOREBOARD_DEPTH; i = i + 1) scoreboard_q[i] <= '0;
            for (i = 0; i < STORE_BUFFER_DEPTH; i = i + 1) store_q[i] <= '0;
            for (i = 0; i < LOAD_QUEUE_DEPTH; i = i + 1) load_q[i] <= '0;
        end else begin
            wb_valid_q <= commit_normal && commit_entry.writes_rd && commit_entry.rd != 0;
            if (commit_normal && commit_entry.writes_rd && commit_entry.rd != 0) begin
                wb_rd_q <= commit_entry.rd;
                wb_data_q <= (commit_entry.sys_op == SYS_CSR) ? csr_result :
                             commit_entry.result;
            end
            // Recovery/predictor control is registered so an EX operand compare
            // cannot drive global redirect/allocation enables in the same
            // cycle.  Issue pauses for the branch's EX cycle above, preserving
            // correctness without adding speculative backend rollback state.
            branch_resolve_valid <= branch_resolve_valid_c;
            branch_predictor_update_valid_q <= branch_resolve_valid_c &&
                                               !fixed_completion.exception_valid;
            branch_miss <= branch_miss_c;
            if (branch_resolve_valid_c) begin
                branch_taken <= branch_taken_c;
                branch_target <= branch_target_c;
                branch_actual_next <= branch_actual_next_c;
                branch_pc_q <= exec_q.uop.pc;
                branch_kind <= branch_kind_c;
            end
            if (full_flush) begin
                issue_ptr_q <= '0;
                commit_ptr_q <= '0;
                scoreboard_count_q <= '0;
                producer_valid_q <= '0;
                serial_pending_q <= 1'b0;
                exec_q.valid <= 1'b0;
                load_head_q <= '0;
                load_tail_q <= '0;
                load_count_q <= '0;
                load_active_q <= 1'b0;
                for (i = 0; i < SCOREBOARD_DEPTH; i = i + 1) scoreboard_q[i].occupied <= 1'b0;
                for (i = 0; i < LOAD_QUEUE_DEPTH; i = i + 1) load_q[i].valid <= 1'b0;
                committed_tmp = 0;
                for (i = 0; i < STORE_BUFFER_DEPTH; i = i + 1) begin
                    if (store_q[i].valid && store_committed_q[i]) begin
                        committed_tmp = committed_tmp + 1;
                    end else begin
                        store_q[i].valid <= 1'b0;
                        store_committed_q[i] <= 1'b0;
                    end
                end
                store_count_q <= ST_CNT_W'(committed_tmp);
                store_tail_q <= store_head_q + STORE_ID_W'(committed_tmp);
            end else begin
                exec_q.valid <= issue_fire && !id_uop_q.exception_valid && id_uop_q.fu != FU_SYSTEM;
                if (issue_fire && !id_uop_q.exception_valid && id_uop_q.fu != FU_SYSTEM) begin
                    exec_q.trans_id <= issue_ptr_q;
                    exec_q.uop <= id_uop_q;
                    exec_q.op1 <= src1_value;
                    exec_q.op2 <= src2_value;
                    // Early AGU retiming: the memory stage receives a
                    // registered effective address instead of placing a
                    // 32-bit add in front of cache metadata/RAM controls.
                    exec_mem_addr_q <= src1_value + id_uop_q.imm;
                end

                if (fixed_completion_valid && scoreboard_q[fixed_completion.trans_id].occupied) begin
                    scoreboard_q[fixed_completion.trans_id].done <= 1'b1;
                    scoreboard_q[fixed_completion.trans_id].result <= fixed_completion.result;
                    scoreboard_q[fixed_completion.trans_id].exception_valid <= fixed_completion.exception_valid;
                    scoreboard_q[fixed_completion.trans_id].exception_cause <= fixed_completion.exception_cause;
                    scoreboard_q[fixed_completion.trans_id].exception_tval <= fixed_completion.exception_tval;
                    scoreboard_q[fixed_completion.trans_id].store_slot_valid <= fixed_completion.store_slot_valid;
                    scoreboard_q[fixed_completion.trans_id].store_slot <= fixed_completion.store_slot;
                end
                if (load_completion_valid && scoreboard_q[load_completion_meta.trans_id].occupied) begin
                    scoreboard_q[load_completion_meta.trans_id].done <= 1'b1;
                    scoreboard_q[load_completion_meta.trans_id].result <= load_result;
                    if (!load_forward_complete) load_active_q <= 1'b0;
                end
                if (mdu_resp_valid && scoreboard_q[mdu_resp_tid].occupied) begin
                    scoreboard_q[mdu_resp_tid].done <= 1'b1;
                    scoreboard_q[mdu_resp_tid].result <= mdu_resp_result;
                end

                if (commit_fire) begin
                    if (commit_store_mark) store_committed_q[commit_entry.store_slot] <= 1'b1;
                    if (commit_entry.writes_rd && commit_entry.rd != 0 &&
                        producer_valid_q[commit_entry.rd] &&
                        producer_tid_q[commit_entry.rd] == commit_ptr_q)
                        producer_valid_q[commit_entry.rd] <= 1'b0;
                    scoreboard_q[commit_ptr_q].occupied <= 1'b0;
                    commit_ptr_q <= commit_ptr_q + 1'b1;
                    if (commit_entry.sys_op != SYS_NONE || commit_entry.exception_valid) serial_pending_q <= 1'b0;
                end

                if (issue_fire) begin
                    scoreboard_q[issue_ptr_q] <= '0;
                    scoreboard_q[issue_ptr_q].occupied <= 1'b1;
                    scoreboard_q[issue_ptr_q].done <= id_uop_q.exception_valid || id_uop_q.fu == FU_SYSTEM;
                    scoreboard_q[issue_ptr_q].pc <= id_uop_q.pc;
                    scoreboard_q[issue_ptr_q].instr <= id_uop_q.instr;
                    scoreboard_q[issue_ptr_q].rd <= id_uop_q.rd;
                    scoreboard_q[issue_ptr_q].writes_rd <= id_uop_q.writes_rd;
                    scoreboard_q[issue_ptr_q].fu <= id_uop_q.fu;
                    scoreboard_q[issue_ptr_q].sys_op <= id_uop_q.sys_op;
                    scoreboard_q[issue_ptr_q].csr_op <= id_uop_q.csr_op;
                    scoreboard_q[issue_ptr_q].csr_addr <= id_uop_q.csr_addr;
                    scoreboard_q[issue_ptr_q].csr_src <= id_uop_q.csr_imm ? {27'd0, id_uop_q.rs1} : src1_value;
                    scoreboard_q[issue_ptr_q].exception_valid <= id_uop_q.exception_valid;
                    scoreboard_q[issue_ptr_q].exception_cause <= id_uop_q.exception_cause;
                    scoreboard_q[issue_ptr_q].exception_tval <= id_uop_q.exception_tval;
                    scoreboard_q[issue_ptr_q].is_call <= (id_uop_q.is_jal || id_uop_q.is_jalr) &&
                                                        (id_uop_q.rd == 5'd1 || id_uop_q.rd == 5'd5);
                    scoreboard_q[issue_ptr_q].is_return <= id_uop_q.is_jalr &&
                                                          (id_uop_q.rs1 == 5'd1 || id_uop_q.rs1 == 5'd5) && id_uop_q.rd == 0;
                    scoreboard_q[issue_ptr_q].link_addr <= id_uop_q.pc + 32'd4;
                    if (id_uop_q.writes_rd && id_uop_q.rd != 0) begin
                        producer_valid_q[id_uop_q.rd] <= 1'b1;
                        producer_tid_q[id_uop_q.rd] <= issue_ptr_q;
                    end
                    issue_ptr_q <= issue_ptr_q + 1'b1;
                    if (id_uop_q.serialize) serial_pending_q <= 1'b1;
                end

                unique case ({issue_fire, commit_fire})
                    2'b10: scoreboard_count_q <= scoreboard_count_q + 1'b1;
                    2'b01: scoreboard_count_q <= scoreboard_count_q - 1'b1;
                    default: begin end
                endcase

                if (exec_store_enqueue) begin
                    store_q[store_tail_q].valid <= 1'b1;
                    store_committed_q[store_tail_q] <= 1'b0;
                    store_q[store_tail_q].trans_id <= exec_q.trans_id;
                    store_q[store_tail_q].store_seq <= next_store_seq_q;
                    store_q[store_tail_q].addr <= exec_mem_addr_q;
                    store_q[store_tail_q].wdata <= exec_q.op2;
                    unique case (exec_q.uop.mem_size)
                        MEM_BYTE: store_q[store_tail_q].wstrb <= 4'b0001;
                        MEM_HALF: store_q[store_tail_q].wstrb <= 4'b0011;
                        default: store_q[store_tail_q].wstrb <= 4'b1111;
                    endcase
                    store_q[store_tail_q].uncached <= !addr_is_dram(exec_mem_addr_q);
                    store_tail_q <= store_tail_q + 1'b1;
                    next_store_seq_q <= next_store_seq_q + 1'b1;
                end
                if (store_drain_fire) begin
                    store_q[store_head_q].valid <= 1'b0;
                    store_committed_q[store_head_q] <= 1'b0;
                    store_head_q <= store_head_q + 1'b1;
                end
                unique case ({exec_store_enqueue, store_drain_fire})
                    2'b10: store_count_q <= store_count_q + 1'b1;
                    2'b01: store_count_q <= store_count_q - 1'b1;
                    default: begin end
                endcase

                if (load_enqueue_fire) begin
                    load_q[load_tail_q].valid <= 1'b1;
                    load_q[load_tail_q].trans_id <= exec_q.trans_id;
                    load_q[load_tail_q].addr <= exec_mem_addr_q;
                    load_q[load_tail_q].size <= exec_q.uop.mem_size;
                    load_q[load_tail_q].load_unsigned <= exec_q.uop.load_unsigned;
                    load_q[load_tail_q].store_seq_cutoff <= next_store_seq_q;
                    load_q[load_tail_q].forward_mask <= load_forward_mask_c;
                    load_q[load_tail_q].forward_data <= load_forward_data_c;
                    load_tail_q <= load_tail_q + 1'b1;
                end
                if (load_direct_start_fire) begin
                    load_active_q <= 1'b1;
                    load_active_meta_q <= load_direct_meta;
                end
                if (load_pop_fire) begin
                    if (load_start_fire) begin
                        load_active_q <= 1'b1;
                        load_active_meta_q <= load_q[load_head_q];
                    end
                    load_q[load_head_q].valid <= 1'b0;
                    load_head_q <= load_head_q + 1'b1;
                end
                unique case ({load_enqueue_fire, load_pop_fire})
                    2'b10: load_count_q <= load_count_q + 1'b1;
                    2'b01: load_count_q <= load_count_q - 1'b1;
                    default: begin end
                endcase
            end
        end
    end

`ifndef SYNTHESIS
    logic dmem_stall_q;
    logic dmem_hold_write_q, dmem_hold_uncached_q;
    logic [31:0] dmem_hold_addr_q, dmem_hold_wdata_q;
    logic [3:0] dmem_hold_wstrb_q;

    always_ff @(posedge clk) begin
        if (rst) begin
            dmem_stall_q <= 1'b0;
            dmem_hold_write_q <= 1'b0;
            dmem_hold_uncached_q <= 1'b0;
            dmem_hold_addr_q <= '0;
            dmem_hold_wdata_q <= '0;
            dmem_hold_wstrb_q <= '0;
        end else begin
            assert (scoreboard_count_q <= SB_CNT_W'(SCOREBOARD_DEPTH));
            assert (store_count_q <= ST_CNT_W'(STORE_BUFFER_DEPTH));
            assert (load_count_q <= LD_CNT_W'(LOAD_QUEUE_DEPTH));
            assert (commit_count_q <= cycle_q);
            assert (branch_miss_count_q <= branch_count_q);
            assert (dcache_miss_q <= dcache_access_q);
            assert (load_count_perf_q + store_count_perf_q <= commit_count_q);
            if (fixed_completion_valid) assert (scoreboard_q[fixed_completion.trans_id].occupied);
            if (load_completion_valid) assert (scoreboard_q[load_completion_meta.trans_id].occupied);
            if (mdu_resp_valid) assert (scoreboard_q[mdu_resp_tid].occupied);
            if (dc_mem_req_valid && dc_mem_req_write) begin
                assert (store_count_q != 0);
                assert (store_q[store_head_q].valid && store_committed_q[store_head_q]);
            end
            if (load_start_fire && dc_req_uncached) begin
                assert (!older_store_pending);
                assert (load_q[load_head_q].trans_id == commit_ptr_q);
            end
            if (dmem_stall_q) begin
                assert (dmem_req_valid_o);
                assert (dmem_req_write_o == dmem_hold_write_q);
                assert (dmem_req_addr_o == dmem_hold_addr_q);
                assert (dmem_req_wdata_o == dmem_hold_wdata_q);
                assert (dmem_req_wstrb_o == dmem_hold_wstrb_q);
                assert (dmem_req_uncached_o == dmem_hold_uncached_q);
            end
            if (branch_miss) assert (!issue_fire);
            dmem_stall_q <= dmem_req_valid_o && !dmem_req_ready_i;
            if (dmem_req_valid_o && !dmem_req_ready_i) begin
                dmem_hold_write_q <= dmem_req_write_o;
                dmem_hold_addr_q <= dmem_req_addr_o;
                dmem_hold_wdata_q <= dmem_req_wdata_o;
                dmem_hold_wstrb_q <= dmem_req_wstrb_o;
                dmem_hold_uncached_q <= dmem_req_uncached_o;
            end
        end
    end
`endif
endmodule
