`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: core_top
// Generated: 2026-07-13
// Source: 053 architecture + 054 implementation plan
module core_top (
    input  logic clk,
    input  logic rst,
    output logic [31:0] irom_addr_o,
    output logic irom_ena_o,
    input  logic [31:0] irom_data_i,
    output logic dmem_req_valid_o,
    input  logic dmem_req_ready_i,
    output logic dmem_req_write_o,
    output logic [31:0] dmem_req_addr_o,
    output logic [31:0] dmem_req_wdata_o,
    output logic [3:0] dmem_req_wstrb_o,
    output logic dmem_req_uncached_o,
    input  logic dmem_resp_valid_i,
    input  logic [31:0] dmem_resp_rdata_i,
    output logic [63:0] perf_cycle_o,
    output logic [63:0] perf_commit_o,
    output logic [63:0] perf_branch_o,
    output logic [63:0] perf_branch_miss_o,
    output logic [63:0] perf_load_o,
    output logic [63:0] perf_store_o,
    output logic [63:0] perf_dcache_access_o,
    output logic [63:0] perf_dcache_miss_o,
    output logic [63:0] perf_stall_front_o,
    output logic [63:0] perf_stall_mem_o,
    output logic [63:0] perf_stall_muldiv_o,
    output logic [63:0] perf_stall_load_use_o
`ifdef VERILATOR_TB
    ,
    output logic        dbg_commit_valid_o,
    output logic [31:0] dbg_commit_pc_o,
    output logic [31:0] dbg_commit_inst_o,
    output logic        dbg_commit_wen_o,
    output logic [4:0]  dbg_commit_rd_o,
    output logic [31:0] dbg_commit_wdata_o,
    output logic        dbg_commit_is_load_o,
    output logic        dbg_commit_is_store_o,
    output logic        dbg_commit_is_trap_o,
    output logic [31:0] dbg_commit_cause_o,
    output logic [31:0] dbg_commit_next_pc_o,
    output logic [31:0] dbg_commit_mem_addr_o,
    output logic [31:0] dbg_commit_mem_wdata_o,
    output logic [3:0]  dbg_commit_mem_wstrb_o
`endif
);
    import core_config_pkg::*;
    import core_types_pkg::*;

    localparam int unsigned SB_CNT_W = $clog2(SCOREBOARD_DEPTH + 1);
    localparam int unsigned ST_CNT_W = $clog2(STORE_BUFFER_DEPTH + 1);
    localparam int unsigned LD_CNT_W = $clog2(LOAD_QUEUE_DEPTH + 1);
    localparam int unsigned ISSUE_QUEUE_DEPTH = 3;
    localparam int unsigned IQ_CNT_W = $clog2(ISSUE_QUEUE_DEPTH + 1);

    typedef struct packed {
        logic miss;
        logic [31:0] actual_next;
    } branch_outcome_t;

    uop_t id_uop_q, decoded_uop;
    fetch_entry_t fetch_head_entry;
    logic fetch_valid, fetch_pop;
    logic dispatch_fire, dispatch_exec_c, dispatch_ready_c;
    logic [IQ_CNT_W-1:0] issue_queue_count_q;

    logic [31:0] rf_rs1_data, rf_rs2_data, rf_write_data;
    logic rf_write_valid;
    logic wb_valid_q;
    logic [4:0] wb_rd_q;
    logic [31:0] wb_data_q;
    logic [TRANS_ID_W-1:0] dispatch_ptr_q, issue_ptr_q, commit_ptr_q;
    logic [SB_CNT_W-1:0] scoreboard_count_q;
    logic serial_pending_q;
    logic sb_src1_ready, sb_src2_ready;
    logic [31:0] sb_src1_data, sb_src2_data;

    exec_req_t exec_q;
    completion_t fixed_completion;
    logic fixed_completion_valid;
    logic branch_resolve_valid_c, branch_taken_c;
    logic [31:0] branch_target_c, branch_actual_next_c;
    pred_kind_e branch_kind_c;
    logic branch_resolve_valid, branch_taken, branch_miss;
    logic branch_predictor_update_valid_q;
    logic [31:0] branch_target, branch_actual_next, branch_pc_q;
    pred_kind_e branch_kind;
    logic [1:0] branch_pred_counter;
    logic [GSHARE_HISTORY_BITS-1:0] branch_pred_index;
    branch_outcome_t branch_outcome_q [0:SCOREBOARD_DEPTH-1];
    branch_outcome_t commit_branch_outcome_c;
    logic branch_commit_valid_c;

    store_entry_t store_q [0:STORE_BUFFER_DEPTH-1];
    logic [STORE_BUFFER_DEPTH-1:0] store_committed_q;
    logic [STORE_ID_W-1:0] store_head_q, store_tail_q;
    logic [ST_CNT_W-1:0] store_count_q;
    logic [7:0] next_store_seq_q;
    logic [LD_CNT_W-1:0] load_count_q;
    logic load_active_q;
    load_entry_t load_active_meta_q;

    logic [31:0] src1_value, src2_value, src1_mem_value;
    logic src1_ready, src2_ready, src1_mem_ready, src1_found, src2_found;
    logic [TRANS_ID_W-1:0] src1_tid, src2_tid;
    logic [31:0] csr_src_value;
    logic issue_fire;
    logic [31:0] issue_src1_c, issue_src2_c;
    logic issue_src1_load_bypass_c, issue_src2_load_bypass_c;
    logic exec_src1_load_bypass_q, exec_src2_load_bypass_q;
    logic [31:0] load_issue_bypass_data_q;
    logic issue_memory_addr_valid_c;
    logic [31:0] issue_memory_addr_c;
    logic iq_load_ready_c, iq_store_ready_c, iq_muldiv_ready_c;
    logic iq_bitmanip_ready_c, iq_issue_block_c;
    logic exec_load_enqueue, exec_store_enqueue;
    logic [31:0] exec_mem_addr_calc, exec_mem_addr_q;
    exec_req_t exec_effective_c;

    logic dc_req_valid, dc_req_ready, dc_req_write, dc_req_uncached;
    logic [31:0] dc_req_addr, dc_req_wdata;
    logic [3:0] dc_req_wstrb;
    logic dc_resp_valid, dc_idle, dc_access_pulse, dc_miss_pulse;
    logic [31:0] dc_resp_rdata;
    logic dc_mem_req_valid, dc_mem_req_ready, dc_mem_req_write, dc_mem_req_uncached;
    logic [31:0] dc_mem_req_addr, dc_mem_req_wdata;
    logic [3:0] dc_mem_req_wstrb;
    logic dc_mem_resp_valid;
    logic [31:0] dc_mem_resp_rdata;
    logic store_drain_fire, load_start_fire;
    logic older_store_pending;
    logic [31:0] load_result;
    logic [31:0] load_forward_data_c;
    logic [3:0] load_forward_mask_c;
    logic load_completion_valid, load_completion_accepted;
    logic load_forward_complete, load_pop_fire;
    logic load_direct_candidate, load_direct_start_fire, load_queue_start_fire;
    logic load_enqueue_fire, direct_older_store_pending;
    load_entry_t load_head, load_completion_meta, load_direct_meta, load_enqueue_meta;

    logic mdu_req_valid, mdu_req_ready, mdu_resp_valid, mdu_busy;
    logic [TRANS_ID_W-1:0] mdu_resp_tid;
    logic [31:0] mdu_resp_result;
    logic bm_req_valid, bm_req_ready, bm_resp_valid, bm_busy;
    logic [TRANS_ID_W-1:0] bm_resp_tid, slow_resp_tid;
    logic [31:0] bm_resp_result, slow_resp_result;
    logic slow_resp_valid, bitmanip_clmul_start_c;

    scoreboard_entry_t commit_entry;
    logic commit_ready, commit_fire, commit_normal;
    logic commit_store_mark;
    logic full_flush, redirect_valid;
    logic [31:0] redirect_target;
    logic mem_quiescent;

    logic [11:0] csr_read_addr, csr_write_addr;
    logic [31:0] csr_read_data, csr_write_data, csr_result;
    logic csr_write_valid, csr_trap_valid, csr_mret_valid;
    logic [31:0] csr_mtvec, csr_mepc;

    logic predictor_update_valid, predictor_commit_call, predictor_commit_return;
    logic [31:0] predictor_update_target;

    logic [63:0] cycle_q, commit_count_q, branch_count_q, branch_miss_count_q;
    logic [63:0] load_count_perf_q, store_count_perf_q;
    logic [63:0] dcache_access_q, dcache_miss_q;
    logic [63:0] stall_front_q, stall_mem_q, stall_muldiv_q, stall_load_use_q;
    logic stall_front_c, stall_mem_c, stall_muldiv_c, stall_raw_c;

    function automatic logic addr_is_dram(input logic [31:0] addr);
        begin
            // DRAM is a naturally aligned 256 KiB window at 0x8010_0000.
            addr_is_dram = addr[31:18] == DRAM_START[31:18];
        end
    endfunction

    assign perf_cycle_o = cycle_q;
    assign perf_commit_o = commit_count_q;
    assign perf_branch_o = branch_count_q;
    assign perf_branch_miss_o = branch_miss_count_q;
    assign perf_load_o = load_count_perf_q;
    assign perf_store_o = store_count_perf_q;
    assign perf_dcache_access_o = dcache_access_q;
    assign perf_dcache_miss_o = dcache_miss_q;
    assign perf_stall_front_o = stall_front_q;
    assign perf_stall_mem_o = stall_mem_q;
    assign perf_stall_muldiv_o = stall_muldiv_q;
    assign perf_stall_load_use_o = stall_load_use_q;

    assign stall_raw_c = issue_queue_count_q != 0 && !issue_fire;
    assign stall_mem_c = issue_queue_count_q != 0 && !iq_load_ready_c;
    assign stall_muldiv_c = issue_queue_count_q != 0 &&
                            (!iq_muldiv_ready_c || !iq_bitmanip_ready_c);
    assign stall_front_c = fetch_valid && !dispatch_fire;

    perf_counters u_perf_counters (
        .clk(clk), .rst(rst), .commit_i(commit_normal),
        .commit_load_i(commit_normal && commit_entry.fu == FU_LOAD),
        .commit_store_i(commit_normal && commit_entry.fu == FU_STORE),
        .branch_i(branch_resolve_valid), .branch_miss_i(branch_miss),
        .dcache_access_i(dc_access_pulse), .dcache_miss_i(dc_miss_pulse),
        .stall_front_i(stall_front_c), .stall_mem_i(stall_mem_c),
        .stall_muldiv_i(stall_muldiv_c), .stall_raw_i(stall_raw_c),
        .cycle_o(cycle_q), .commit_o(commit_count_q), .branch_o(branch_count_q),
        .branch_miss_o(branch_miss_count_q), .load_o(load_count_perf_q),
        .store_o(store_count_perf_q), .dcache_access_o(dcache_access_q),
        .dcache_miss_o(dcache_miss_q), .stall_front_o(stall_front_q),
        .stall_mem_o(stall_mem_q), .stall_muldiv_o(stall_muldiv_q),
        .stall_raw_o(stall_load_use_q)
    );

    assign dispatch_exec_c = !decoded_uop.exception_valid &&
                             decoded_uop.fu != FU_SYSTEM;
    assign dispatch_ready_c = !serial_pending_q &&
        (scoreboard_count_q < SB_CNT_W'(SCOREBOARD_DEPTH) || commit_fire) &&
        (dispatch_exec_c ? issue_queue_count_q < IQ_CNT_W'(ISSUE_QUEUE_DEPTH) :
         (scoreboard_count_q == 0 && issue_queue_count_q == 0)) &&
        (!(decoded_uop.serialize || decoded_uop.exception_valid) ||
         (scoreboard_count_q == 0 && issue_queue_count_q == 0));
    assign dispatch_fire = fetch_valid && dispatch_ready_c && !redirect_valid;
    assign fetch_pop = dispatch_fire;

    frontend u_frontend (
        .clk(clk), .rst(rst), .redirect_valid_i(redirect_valid),
        .redirect_target_i(redirect_target), .irom_addr_o(irom_addr_o),
        .irom_ena_o(irom_ena_o), .irom_data_i(irom_data_i),
        .fetch_valid_o(fetch_valid), .fetch_entry_o(fetch_head_entry),
        .fetch_ready_i(fetch_pop), .predictor_update_valid_i(predictor_update_valid),
        .predictor_update_pc_i(branch_pc_q), .predictor_update_taken_i(branch_taken),
        .predictor_update_target_i(predictor_update_target),
        .predictor_update_kind_i(branch_kind),
        .predictor_update_pred_counter_i(branch_pred_counter),
        .predictor_update_pred_index_i(branch_pred_index),
        .predictor_commit_call_i(predictor_commit_call),
        .predictor_commit_return_i(predictor_commit_return),
        .predictor_commit_link_i(commit_entry.link_addr)
    );

    decoder u_decoder (.fetch_i(fetch_head_entry), .uop_o(decoded_uop));

    assign rf_write_valid = wb_valid_q;
    assign rf_write_data = wb_data_q;
    regfile u_regfile (
        .clk(clk), .rst(rst), .rs1_addr_i(decoded_uop.rs1), .rs2_addr_i(decoded_uop.rs2),
        .rs1_data_o(rf_rs1_data), .rs2_data_o(rf_rs2_data),
        .write_valid_i(rf_write_valid), .write_addr_i(wb_rd_q),
        .write_data_i(rf_write_data)
    );

    scoreboard u_scoreboard (
        .clk(clk), .rst(rst), .flush_i(full_flush),
        .allocate_i(dispatch_fire), .allocate_uop_i(decoded_uop),
        .allocate_csr_src_i(csr_src_value), .allocate_trans_id_o(dispatch_ptr_q),
        .fixed_complete_i(fixed_completion_valid),
        .fixed_completion_i(fixed_completion),
        .load_complete_i(load_completion_valid),
        .load_trans_id_i(load_completion_meta.trans_id),
        .load_result_i(load_result),
        .load_complete_accepted_o(load_completion_accepted),
        .slow_complete_i(slow_resp_valid),
        .slow_trans_id_i(slow_resp_tid), .slow_result_i(slow_resp_result),
        .commit_i(commit_fire), .commit_trans_id_o(commit_ptr_q),
        .commit_entry_o(commit_entry), .count_o(scoreboard_count_q),
        .serial_pending_o(serial_pending_q), .query_uop_i(decoded_uop),
        .query_rs1_found_o(src1_found), .query_rs1_ready_o(sb_src1_ready),
        .query_rs1_trans_id_o(src1_tid), .query_rs1_data_o(sb_src1_data),
        .query_rs2_found_o(src2_found), .query_rs2_ready_o(sb_src2_ready),
        .query_rs2_trans_id_o(src2_tid), .query_rs2_data_o(sb_src2_data)
    );

    operand_resolver u_operand_resolver (
        .uop_i(decoded_uop), .rf_rs1_data_i(rf_rs1_data),
        .rf_rs2_data_i(rf_rs2_data), .wb_valid_i(wb_valid_q),
        .wb_rd_i(wb_rd_q), .wb_data_i(wb_data_q),
        .rs1_found_i(src1_found), .rs1_scoreboard_ready_i(sb_src1_ready),
        .rs1_trans_id_i(src1_tid), .rs1_scoreboard_data_i(sb_src1_data),
        .rs2_found_i(src2_found), .rs2_scoreboard_ready_i(sb_src2_ready),
        .rs2_trans_id_i(src2_tid), .rs2_scoreboard_data_i(sb_src2_data),
        .fixed_completion_valid_i(fixed_completion_valid),
        .fixed_completion_i(fixed_completion),
        // A completing load wakes entries already resident in the IQ.  Decode
        // does not consume the DCache bypass directly; a same-cycle new
        // consumer enters tagged and wakes from the IQ's registered copy.
        .load_completion_valid_i(1'b0),
        .load_completion_meta_i('0), .load_result_i(32'd0),
        .slow_completion_valid_i(slow_resp_valid),
        .slow_completion_trans_id_i(slow_resp_tid),
        .slow_completion_result_i(slow_resp_result),
        .src1_value_o(src1_value), .src2_value_o(src2_value),
        .src1_memory_value_o(src1_mem_value), .src1_ready_o(src1_ready),
        .src2_ready_o(src2_ready), .src1_memory_ready_o(src1_mem_ready),
        .src1_found_o(), .src2_found_o()
    );

    // CSR instructions are serialized and therefore cannot have an in-flight
    // producer.  Use RF plus the one-cycle architectural-WB bypass directly;
    // routing the general completion bypass into csr_src created hundreds of
    // false-by-construction DCache-data paths.
    always_comb begin
        csr_src_value = decoded_uop.rs1 == 0 ? 32'd0 : rf_rs1_data;
        if (wb_valid_q && decoded_uop.rs1 == wb_rd_q && decoded_uop.rs1 != 0)
            csr_src_value = wb_data_q;
    end

    assign iq_load_ready_c =
        (load_count_q + LD_CNT_W'(exec_q.valid && exec_q.uop.fu == FU_LOAD)) <
        LD_CNT_W'(LOAD_QUEUE_DEPTH);
    assign iq_store_ready_c =
        (store_count_q + ST_CNT_W'(exec_q.valid && exec_q.uop.fu == FU_STORE)) <
        ST_CNT_W'(STORE_BUFFER_DEPTH);
    assign iq_muldiv_ready_c = mdu_req_ready && !bm_busy &&
        !(exec_q.valid && exec_q.uop.fu == FU_MULDIV) && !bitmanip_clmul_start_c;
    assign iq_bitmanip_ready_c = bm_req_ready && !mdu_busy &&
        !(exec_q.valid && exec_q.uop.fu == FU_MULDIV) && !bitmanip_clmul_start_c;
    assign iq_issue_block_c = redirect_valid || serial_pending_q;

    inorder_issue_queue #(.DEPTH(ISSUE_QUEUE_DEPTH)) u_issue_queue (
        .clk(clk), .rst(rst), .flush_i(full_flush),
        .enqueue_i(dispatch_fire && dispatch_exec_c),
        .enqueue_uop_i(decoded_uop), .enqueue_trans_id_i(dispatch_ptr_q),
        .enqueue_src1_ready_i((decoded_uop.fu == FU_LOAD ||
                               decoded_uop.fu == FU_STORE) ?
                              src1_mem_ready : src1_ready),
        .enqueue_src1_trans_id_i(src1_tid),
        .enqueue_src1_value_i((decoded_uop.fu == FU_LOAD ||
                               decoded_uop.fu == FU_STORE) ?
                              src1_mem_value : src1_value),
        .enqueue_src2_ready_i(src2_ready),
        .enqueue_src2_trans_id_i(src2_tid),
        .enqueue_src2_value_i(src2_value),
        .fixed_complete_i(fixed_completion_valid),
        .fixed_completion_i(fixed_completion),
        .fixed_mem_addr_defer_i(exec_src1_load_bypass_q ||
                                exec_src2_load_bypass_q),
        .load_complete_i(load_completion_valid),
        .load_trans_id_i(load_completion_meta.trans_id), .load_result_i(load_result),
        .slow_complete_i(slow_resp_valid), .slow_trans_id_i(slow_resp_tid),
        .slow_result_i(slow_resp_result), .load_ready_i(iq_load_ready_c),
        .store_ready_i(iq_store_ready_c), .muldiv_ready_i(iq_muldiv_ready_c),
        .bitmanip_ready_i(iq_bitmanip_ready_c), .issue_block_i(iq_issue_block_c),
        .commit_trans_id_i(commit_ptr_q), .issue_valid_o(issue_fire),
        .issue_uop_o(id_uop_q), .issue_trans_id_o(issue_ptr_q),
        .issue_src1_o(issue_src1_c), .issue_src2_o(issue_src2_c),
        .issue_src1_load_bypass_o(issue_src1_load_bypass_c),
        .issue_src2_load_bypass_o(issue_src2_load_bypass_c),
        .memory_addr_valid_o(issue_memory_addr_valid_c),
        .memory_addr_o(issue_memory_addr_c),
        .count_o(issue_queue_count_q)
    );

    always_comb begin
        exec_effective_c = exec_q;
        if (exec_src1_load_bypass_q)
            exec_effective_c.op1 = load_issue_bypass_data_q;
        if (exec_src2_load_bypass_q)
            exec_effective_c.op2 = load_issue_bypass_data_q;
    end

    fixed_execute u_fixed_execute (
        .exec_i(exec_effective_c), .store_tail_i(store_tail_q),
        .completion_valid_o(fixed_completion_valid), .completion_o(fixed_completion),
        .branch_resolve_valid_o(branch_resolve_valid_c), .branch_taken_o(branch_taken_c),
        .branch_target_o(branch_target_c), .branch_actual_next_o(branch_actual_next_c),
        .branch_kind_o(branch_kind_c), .load_enqueue_o(exec_load_enqueue),
        .store_enqueue_o(exec_store_enqueue), .mem_addr_o(exec_mem_addr_calc)
    );

    assign commit_branch_outcome_c = branch_outcome_q[commit_ptr_q];
    assign branch_commit_valid_c = commit_normal && commit_entry.fu == FU_BRANCH;
    assign branch_resolve_valid = branch_commit_valid_c;
    assign branch_miss = branch_commit_valid_c && commit_branch_outcome_c.miss;
    assign branch_actual_next = commit_branch_outcome_c.actual_next;
    // Predictor state is performance-only and can train when a branch
    // executes.  Only precise recovery data is retained until commit.
    assign predictor_update_valid = branch_predictor_update_valid_q;
    assign predictor_update_target = branch_target;

    store_forwarding u_store_forwarding (
        .load_valid_i(exec_load_enqueue),
        .load_cacheable_i(addr_is_dram(exec_mem_addr_q)),
        .load_addr_i(exec_mem_addr_q), .store_entries_i(store_q),
        .store_head_i(store_head_q), .store_count_i(store_count_q),
        .forward_mask_o(load_forward_mask_c),
        .forward_data_o(load_forward_data_c)
    );

    muldiv_unit u_muldiv (
        .clk(clk), .rst(rst), .kill_i(full_flush),
        .req_valid_i(mdu_req_valid), .req_ready_o(mdu_req_ready),
        .req_trans_id_i(exec_q.trans_id), .req_op_i(exec_q.uop.muldiv_op),
        .req_a_i(exec_effective_c.op1), .req_b_i(exec_effective_c.op2),
        .resp_valid_o(mdu_resp_valid), .resp_trans_id_o(mdu_resp_tid),
        .resp_result_o(mdu_resp_result), .busy_o(mdu_busy)
    );
    assign mdu_req_valid = exec_q.valid && exec_q.uop.fu == FU_MULDIV && !full_flush;

    bitmanip_unit u_bitmanip (
        .clk(clk), .rst(rst), .kill_i(full_flush),
        .req_valid_i(bm_req_valid), .req_ready_o(bm_req_ready),
        .req_trans_id_i(exec_q.trans_id), .req_op_i(exec_q.uop.bitmanip_op),
        .req_a_i(exec_effective_c.op1),
        .req_b_i(exec_q.uop.uses_rs2 ? exec_effective_c.op2 : exec_q.uop.imm),
        .resp_valid_o(bm_resp_valid), .resp_trans_id_o(bm_resp_tid),
        .resp_result_o(bm_resp_result), .busy_o(bm_busy)
    );
    assign bm_req_valid = exec_q.valid && exec_q.uop.fu == FU_BITMANIP && !full_flush;
    assign bitmanip_clmul_start_c = bm_req_valid &&
        (exec_q.uop.bitmanip_op == BM_CLMUL ||
         exec_q.uop.bitmanip_op == BM_CLMULH ||
         exec_q.uop.bitmanip_op == BM_CLMULR);

    // Bitmanip and MDU issue are mutually exclusive while either iterative
    // engine is busy, so they can share the existing long-latency wakeup port.
    assign slow_resp_valid = mdu_resp_valid || bm_resp_valid;
    assign slow_resp_tid = bm_resp_valid ? bm_resp_tid : mdu_resp_tid;
    assign slow_resp_result = bm_resp_valid ? bm_resp_result : mdu_resp_result;

    store_buffer u_store_buffer (
        .clk(clk), .rst(rst), .flush_i(full_flush),
        .enqueue_i(exec_store_enqueue), .enqueue_trans_id_i(exec_q.trans_id),
        .enqueue_addr_i(exec_mem_addr_q), .enqueue_wdata_i(exec_effective_c.op2),
        .enqueue_size_i(exec_q.uop.mem_size),
        .enqueue_uncached_i(!addr_is_dram(exec_mem_addr_q)),
        .commit_i(commit_store_mark), .commit_slot_i(commit_entry.store_slot),
        .drain_i(store_drain_fire), .entries_o(store_q),
        .committed_o(store_committed_q), .head_o(store_head_q),
        .tail_o(store_tail_q), .count_o(store_count_q),
        .next_sequence_o(next_store_seq_q)
    );

    memory_request_arbiter u_memory_request_arbiter (
        .flush_i(full_flush), .commit_trans_id_i(commit_ptr_q),
        .store_entries_i(store_q), .store_committed_i(store_committed_q),
        .store_head_i(store_head_q), .store_count_i(store_count_q),
        .next_store_sequence_i(next_store_seq_q), .load_head_i(load_head),
        .load_count_i(load_count_q),
        .load_forward_complete_i(load_forward_complete),
        .exec_load_valid_i(exec_load_enqueue), .exec_trans_id_i(exec_q.trans_id),
        .exec_addr_i(exec_mem_addr_q), .request_valid_o(dc_req_valid),
        .request_write_o(dc_req_write), .request_addr_o(dc_req_addr),
        .request_wdata_o(dc_req_wdata), .request_wstrb_o(dc_req_wstrb),
        .request_uncached_o(dc_req_uncached),
        .load_direct_candidate_o(load_direct_candidate),
        .older_store_pending_o(older_store_pending),
        .direct_older_store_pending_o(direct_older_store_pending)
    );

    assign store_drain_fire = dc_req_valid && dc_req_write && dc_req_ready;
    assign load_start_fire = dc_req_valid && !dc_req_write && dc_req_ready;
    assign load_direct_start_fire = load_start_fire && load_direct_candidate;
    assign load_queue_start_fire = load_start_fire && !load_direct_candidate;
    assign load_pop_fire = load_queue_start_fire || load_forward_complete;
    assign load_enqueue_fire = exec_load_enqueue && !load_direct_start_fire;
    always_comb begin
        load_direct_meta = '0;
        load_direct_meta.valid = 1'b1;
        load_direct_meta.trans_id = exec_q.trans_id;
        load_direct_meta.addr = exec_mem_addr_q;
        load_direct_meta.size = exec_q.uop.mem_size;
        load_direct_meta.load_unsigned = exec_q.uop.load_unsigned;
        load_direct_meta.store_seq_cutoff = next_store_seq_q;
        load_direct_meta.forward_mask = load_forward_mask_c;
        load_direct_meta.forward_data = load_forward_data_c;
        load_enqueue_meta = load_direct_meta;
    end

    load_data_path u_load_data_path (
        .load_active_i(load_active_q), .load_count_i(load_count_q),
        .load_head_i(load_head), .active_meta_i(load_active_meta_q),
        .memory_data_i(dc_resp_rdata),
        .forward_complete_o(load_forward_complete),
        .completion_meta_o(load_completion_meta), .result_o(load_result)
    );
    assign load_completion_valid = (dc_resp_valid && load_active_q) || load_forward_complete;

    load_queue u_load_queue (
        .clk(clk), .rst(rst), .flush_i(full_flush),
        .completion_i(load_completion_accepted),
        .forward_completion_i(load_forward_complete),
        .direct_start_i(load_direct_start_fire), .direct_meta_i(load_direct_meta),
        .pop_i(load_pop_fire), .memory_start_i(load_start_fire),
        .enqueue_i(load_enqueue_fire), .enqueue_meta_i(load_enqueue_meta),
        .head_o(load_head), .count_o(load_count_q), .active_o(load_active_q),
        .active_meta_o(load_active_meta_q)
    );

    dcache u_dcache (
        .clk(clk), .rst(rst), .kill_i(full_flush),
        .cpu_req_valid_i(dc_req_valid), .cpu_req_ready_o(dc_req_ready),
        .cpu_req_write_i(dc_req_write), .cpu_req_addr_i(dc_req_addr),
        .cpu_req_wdata_i(dc_req_wdata), .cpu_req_wstrb_i(dc_req_wstrb),
        .cpu_req_uncached_i(dc_req_uncached), .cpu_resp_valid_o(dc_resp_valid),
        .cpu_resp_rdata_o(dc_resp_rdata), .mem_req_valid_o(dc_mem_req_valid),
        .mem_req_ready_i(dc_mem_req_ready), .mem_req_write_o(dc_mem_req_write),
        .mem_req_addr_o(dc_mem_req_addr), .mem_req_wdata_o(dc_mem_req_wdata),
        .mem_req_wstrb_o(dc_mem_req_wstrb), .mem_req_uncached_o(dc_mem_req_uncached),
        .mem_resp_valid_i(dc_mem_resp_valid), .mem_resp_rdata_i(dc_mem_resp_rdata),
        .access_pulse_o(dc_access_pulse), .miss_pulse_o(dc_miss_pulse), .idle_o(dc_idle)
    );

    dmem_regslice u_dmem_regslice (
        .clk(clk), .rst(rst),
        .s_req_valid_i(dc_mem_req_valid), .s_req_ready_o(dc_mem_req_ready),
        .s_req_write_i(dc_mem_req_write), .s_req_addr_i(dc_mem_req_addr),
        .s_req_wdata_i(dc_mem_req_wdata), .s_req_wstrb_i(dc_mem_req_wstrb),
        .s_req_uncached_i(dc_mem_req_uncached),
        .s_resp_valid_o(dc_mem_resp_valid), .s_resp_rdata_o(dc_mem_resp_rdata),
        .m_req_valid_o(dmem_req_valid_o), .m_req_ready_i(dmem_req_ready_i),
        .m_req_write_o(dmem_req_write_o), .m_req_addr_o(dmem_req_addr_o),
        .m_req_wdata_o(dmem_req_wdata_o), .m_req_wstrb_o(dmem_req_wstrb_o),
        .m_req_uncached_o(dmem_req_uncached_o),
        .m_resp_valid_i(dmem_resp_valid_i), .m_resp_rdata_i(dmem_resp_rdata_i)
    );

    assign mem_quiescent = (store_count_q == 0) && (load_count_q == 0) &&
                           !load_active_q && dc_idle && !mdu_busy;
    always_comb begin
        commit_ready = commit_entry.occupied && commit_entry.done;
        if (commit_entry.fu == FU_STORE && commit_entry.store_slot_valid)
            commit_ready = commit_ready && store_q[commit_entry.store_slot].valid;
        if (commit_entry.sys_op == SYS_FENCE || commit_entry.sys_op == SYS_FENCE_I)
            commit_ready = commit_ready && mem_quiescent;
    end
    assign commit_fire = commit_ready;
    assign commit_normal = commit_fire && !commit_entry.exception_valid;
    assign commit_store_mark = commit_normal && commit_entry.fu == FU_STORE && commit_entry.store_slot_valid;
    recovery_ctrl u_recovery_ctrl (
        .commit_fire_i(commit_fire), .commit_entry_i(commit_entry),
        .mtvec_i(csr_mtvec), .mepc_i(csr_mepc), .branch_miss_i(branch_miss),
        .branch_actual_next_i(branch_actual_next), .full_flush_o(full_flush),
        .redirect_valid_o(redirect_valid), .redirect_target_o(redirect_target)
    );

    assign csr_read_addr = commit_entry.csr_addr;
    always_comb begin
        unique case (commit_entry.csr_op)
            CSR_WRITE: csr_write_data = commit_entry.csr_src;
            CSR_SET: csr_write_data = csr_read_data | commit_entry.csr_src;
            CSR_CLEAR: csr_write_data = csr_read_data & ~commit_entry.csr_src;
            default: csr_write_data = csr_read_data;
        endcase
        csr_result = csr_read_data;
    end
    assign csr_write_valid = commit_normal && commit_entry.sys_op == SYS_CSR &&
                             (commit_entry.csr_op == CSR_WRITE || commit_entry.csr_src != 0);
    assign csr_write_addr = commit_entry.csr_addr;
    assign csr_trap_valid = commit_fire && commit_entry.exception_valid;
    assign csr_mret_valid = commit_normal && commit_entry.sys_op == SYS_MRET;

    csr_file u_csr (
        .clk(clk), .rst(rst), .read_addr_i(csr_read_addr), .read_data_o(csr_read_data),
        .write_valid_i(csr_write_valid), .write_addr_i(csr_write_addr),
        .write_data_i(csr_write_data), .trap_valid_i(csr_trap_valid),
        .trap_pc_i(commit_entry.pc), .trap_cause_i(commit_entry.exception_cause),
        .trap_tval_i(commit_entry.exception_tval), .mret_valid_i(csr_mret_valid),
        .cycle_i(cycle_q), .instret_i(commit_count_q), .mtvec_o(csr_mtvec), .mepc_o(csr_mepc)
    );

    assign predictor_commit_call = commit_normal && commit_entry.is_call;
    assign predictor_commit_return = commit_normal && commit_entry.is_return;

`ifdef VERILATOR_TB
    commit_trace_probe u_commit_trace_probe (
        .clk(clk), .rst(rst), .commit_i(commit_fire),
        .commit_normal_i(commit_normal), .commit_entry_i(commit_entry),
        .commit_trans_id_i(commit_ptr_q), .csr_result_i(csr_result),
        .csr_mtvec_i(csr_mtvec), .csr_mepc_i(csr_mepc),
        .issue_i(issue_fire), .issue_trans_id_i(issue_ptr_q),
        .issue_uop_i(id_uop_q), .branch_resolve_i(branch_resolve_valid_c),
        .branch_actual_next_i(branch_actual_next_c), .exec_i(exec_effective_c),
        .exec_mem_addr_i(exec_mem_addr_q), .cycle_i(cycle_q),
        .commit_count_i(commit_count_q),
        .commit_valid_o(dbg_commit_valid_o), .commit_pc_o(dbg_commit_pc_o),
        .commit_inst_o(dbg_commit_inst_o), .commit_wen_o(dbg_commit_wen_o),
        .commit_rd_o(dbg_commit_rd_o), .commit_wdata_o(dbg_commit_wdata_o),
        .commit_is_load_o(dbg_commit_is_load_o),
        .commit_is_store_o(dbg_commit_is_store_o),
        .commit_is_trap_o(dbg_commit_is_trap_o),
        .commit_cause_o(dbg_commit_cause_o),
        .commit_next_pc_o(dbg_commit_next_pc_o),
        .commit_mem_addr_o(dbg_commit_mem_addr_o),
        .commit_mem_wdata_o(dbg_commit_mem_wdata_o),
        .commit_mem_wstrb_o(dbg_commit_mem_wstrb_o)
    );
`endif

    always_ff @(posedge clk) begin
        if (rst) begin
            wb_valid_q <= 1'b0;
            wb_rd_q <= '0;
            wb_data_q <= '0;
            exec_q <= '0;
            exec_src1_load_bypass_q <= 1'b0;
            exec_src2_load_bypass_q <= 1'b0;
            load_issue_bypass_data_q <= '0;
            exec_mem_addr_q <= '0;
            branch_predictor_update_valid_q <= 1'b0;
            branch_taken <= 1'b0;
            branch_target <= '0;
            branch_pc_q <= '0;
            branch_kind <= PRED_NONE;
            branch_pred_counter <= 2'b01;
            branch_pred_index <= '0;
        end else begin
            wb_valid_q <= commit_normal && commit_entry.writes_rd && commit_entry.rd != 0;
            if (commit_normal && commit_entry.writes_rd && commit_entry.rd != 0) begin
                wb_rd_q <= commit_entry.rd;
                wb_data_q <= (commit_entry.sys_op == SYS_CSR) ? csr_result :
                             commit_entry.result;
            end
            branch_predictor_update_valid_q <= branch_resolve_valid_c &&
                                               !fixed_completion.exception_valid;
            if (branch_resolve_valid_c) begin
                branch_outcome_q[exec_q.trans_id].miss <=
                    !fixed_completion.exception_valid &&
                    branch_actual_next_c != exec_q.uop.pred_next_pc;
                branch_outcome_q[exec_q.trans_id].actual_next <= branch_actual_next_c;
                branch_taken <= branch_taken_c;
                branch_target <= branch_target_c;
                branch_pc_q <= exec_q.uop.pc;
                branch_kind <= branch_kind_c;
                branch_pred_counter <= exec_q.uop.pred_counter;
                branch_pred_index <= exec_q.uop.pred_index;
            end
            if (full_flush) begin
                exec_q.valid <= 1'b0;
                exec_src1_load_bypass_q <= 1'b0;
                exec_src2_load_bypass_q <= 1'b0;
            end else begin
                // Only normal executable uops are enqueued into the IQ, so
                // issue_fire already implies !exception and FU != SYSTEM.
                exec_q.valid <= issue_fire;
                // These tags are payload: they are ignored whenever valid is
                // low and therefore do not need issue_fire in their D paths.
                exec_src1_load_bypass_q <= issue_src1_load_bypass_c;
                exec_src2_load_bypass_q <= issue_src2_load_bypass_c;
            end
            if (load_completion_valid)
                load_issue_bypass_data_q <= load_result;
            // Payload registers sample continuously; only valid is controlled
            // by issue_fire.  This keeps same-cycle load wakeup while removing
            // its high-fanout path to every payload register enable.
            exec_q.trans_id <= issue_ptr_q;
            exec_q.uop <= id_uop_q;
            exec_q.op1 <= issue_src1_c;
            exec_q.op2 <= issue_src2_c;
            // The IQ preselects the oldest memory entry independently from
            // general oldest-ready issue.  A load completion may therefore
            // change ALU selection without driving this AGU register.
            if (issue_memory_addr_valid_c)
                exec_mem_addr_q <= issue_memory_addr_c;
        end
    end

`ifndef SYNTHESIS
    logic dmem_stall_q;
    logic dmem_hold_write_q, dmem_hold_uncached_q;
    logic [31:0] dmem_hold_addr_q, dmem_hold_wdata_q;
    logic [3:0] dmem_hold_wstrb_q;

    always_ff @(posedge clk) begin
        if (rst) begin
            dmem_stall_q <= 1'b0;
            dmem_hold_write_q <= 1'b0;
            dmem_hold_uncached_q <= 1'b0;
            dmem_hold_addr_q <= '0;
            dmem_hold_wdata_q <= '0;
            dmem_hold_wstrb_q <= '0;
        end else begin
            assert (scoreboard_count_q <= SB_CNT_W'(SCOREBOARD_DEPTH));
            assert (store_count_q <= ST_CNT_W'(STORE_BUFFER_DEPTH));
            assert (load_count_q <= LD_CNT_W'(LOAD_QUEUE_DEPTH));
            assert (commit_count_q <= cycle_q);
            assert (branch_miss_count_q <= branch_count_q);
            assert (dcache_miss_q <= dcache_access_q);
            assert (load_count_perf_q + store_count_perf_q <= commit_count_q);
            assert (!(mdu_resp_valid && bm_resp_valid));
            if (dc_mem_req_valid && dc_mem_req_write) begin
                assert (store_count_q != 0);
                assert (store_q[store_head_q].valid && store_committed_q[store_head_q]);
            end
            if (load_start_fire && dc_req_uncached) begin
                if (load_direct_start_fire) begin
                    assert (!direct_older_store_pending);
                    assert (exec_q.trans_id == commit_ptr_q);
                end else begin
                    assert (!older_store_pending);
                    assert (load_head.trans_id == commit_ptr_q);
                end
            end
            if (dmem_stall_q) begin
                assert (dmem_req_valid_o);
                assert (dmem_req_write_o == dmem_hold_write_q);
                assert (dmem_req_addr_o == dmem_hold_addr_q);
                assert (dmem_req_wdata_o == dmem_hold_wdata_q);
                assert (dmem_req_wstrb_o == dmem_hold_wstrb_q);
                assert (dmem_req_uncached_o == dmem_hold_uncached_q);
            end
            if (branch_miss) begin
                assert (commit_entry.fu == FU_BRANCH);
                assert (!issue_fire);
            end
            dmem_stall_q <= dmem_req_valid_o && !dmem_req_ready_i;
            if (dmem_req_valid_o && !dmem_req_ready_i) begin
                dmem_hold_write_q <= dmem_req_write_o;
                dmem_hold_addr_q <= dmem_req_addr_o;
                dmem_hold_wdata_q <= dmem_req_wdata_o;
                dmem_hold_wstrb_q <= dmem_req_wstrb_o;
                dmem_hold_uncached_q <= dmem_req_uncached_o;
            end
        end
    end
`endif
endmodule
