`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: branch_predictor
// Generated: 2026-07-13
// Source: 053 architecture
module branch_predictor #(
    parameter int unsigned ENTRIES   = core_config_pkg::BTB_ENTRIES,
    parameter int unsigned RAS_DEPTH = core_config_pkg::RAS_DEPTH
) (
    input  logic       clk,
    input  logic       rst,
    input  logic       predict_read_en_i,
    input  logic [31:0] predict_pc_i,
    output logic       predict_valid_o,
    output logic [31:0] predict_next_pc_o,
    output core_types_pkg::pred_kind_e predict_kind_o,
    output logic       predict_hit_o,
    output logic [1:0] predict_counter_o,
    input  logic       update_valid_i,
    input  logic [31:0] update_pc_i,
    input  logic       update_taken_i,
    input  logic [31:0] update_target_i,
    input  core_types_pkg::pred_kind_e update_kind_i,
    input  logic       update_pred_hit_i,
    input  logic [1:0] update_pred_counter_i,
    input  logic       commit_call_i,
    input  logic       commit_return_i,
    input  logic [31:0] commit_link_i
);
    import core_types_pkg::*;
    localparam int unsigned INDEX_W = $clog2(ENTRIES);
    localparam int unsigned RAS_W   = $clog2(RAS_DEPTH);
    localparam int unsigned TAG_W   = 32 - INDEX_W - 2;
    localparam int unsigned ENTRY_W = TAG_W + 32 + 2 + 2;

    // Predictor payload is one synchronous simple-dual-port memory.  At 128
    // entries ENTRY_W is 59 bits, which maps naturally to one RAMB36 instead
    // of the former parallel RAM64X1D/RAM64M distributed memories.
    (* ram_style = "block" *) logic [ENTRY_W-1:0] entry_mem [0:ENTRIES-1];
    logic [ENTRIES-1:0] valid_q;
    logic [31:0] ras_q [0:RAS_DEPTH-1];
    logic [RAS_W:0] ras_count_q;
    logic [RAS_W-1:0] ras_top_c;
    logic [INDEX_W-1:0] pred_idx, upd_idx;
    logic [31:0] read_pc_q;
    logic [ENTRY_W-1:0] read_entry_q, update_entry_c;
    logic read_entry_valid_q, read_valid_q;
    logic collision_q;
    logic [ENTRY_W-1:0] collision_entry_q, selected_entry_c;
    logic selected_valid_c;
    logic [TAG_W-1:0] selected_tag_c;
    logic [31:0] selected_target_c;
    pred_kind_e selected_kind_c;
    logic [1:0] selected_counter_c, update_counter_c;

    assign pred_idx = predict_pc_i[INDEX_W+1:2];
    assign upd_idx  = update_pc_i[INDEX_W+1:2];
    assign ras_top_c = RAS_W'(ras_count_q - 1'b1);
    assign update_entry_c = {update_pc_i[31:INDEX_W+2], update_target_i,
                             update_kind_i, update_counter_c};
    assign selected_entry_c = collision_q ? collision_entry_q : read_entry_q;
    assign selected_valid_c = collision_q ? 1'b1 : read_entry_valid_q;
    assign {selected_tag_c, selected_target_c, selected_kind_c,
            selected_counter_c} = selected_entry_c;
    assign predict_valid_o = read_valid_q;
    assign predict_hit_o = read_valid_q && selected_valid_c &&
                           selected_tag_c == read_pc_q[31:INDEX_W+2];

    always_comb begin
        if (update_kind_i != PRED_COND) begin
            update_counter_c = 2'b11;
        end else if (!update_pred_hit_i) begin
            update_counter_c = update_taken_i ? 2'b10 : 2'b01;
        end else if (update_taken_i && update_pred_counter_i != 2'b11) begin
            update_counter_c = update_pred_counter_i + 1'b1;
        end else if (!update_taken_i && update_pred_counter_i != 2'b00) begin
            update_counter_c = update_pred_counter_i - 1'b1;
        end else begin
            update_counter_c = update_pred_counter_i;
        end
    end

    always_comb begin
        predict_next_pc_o = read_pc_q + 32'd4;
        predict_kind_o = PRED_NONE;
        predict_counter_o = selected_counter_c;
        if (predict_hit_o) begin
            predict_kind_o = selected_kind_c;
            unique case (selected_kind_c)
                PRED_COND: if (selected_counter_c[1]) predict_next_pc_o = selected_target_c;
                PRED_RETURN: begin
                    if (ras_count_q != 0) predict_next_pc_o = ras_q[ras_top_c];
                    else predict_next_pc_o = selected_target_c;
                end
                PRED_JUMP: predict_next_pc_o = selected_target_c;
                default: begin end
            endcase
        end
    end

    always_ff @(posedge clk) begin
        if (rst) begin
            valid_q <= '0;
            ras_count_q <= '0;
            read_valid_q <= 1'b0;
            collision_q <= 1'b0;
        end else begin
            read_valid_q <= predict_read_en_i;
            collision_q <= predict_read_en_i && update_valid_i &&
                           pred_idx == upd_idx;
            if (predict_read_en_i) begin
                read_pc_q <= predict_pc_i;
                read_entry_q <= entry_mem[pred_idx];
                read_entry_valid_q <= valid_q[pred_idx];
                collision_entry_q <= update_entry_c;
            end
            if (update_valid_i) begin
                valid_q[upd_idx] <= 1'b1;
                entry_mem[upd_idx] <= update_entry_c;
            end
            if (commit_call_i) begin
                if (ras_count_q < (RAS_W+1)'(RAS_DEPTH)) begin
                    ras_q[ras_count_q[RAS_W-1:0]] <= commit_link_i;
                    ras_count_q <= ras_count_q + 1'b1;
                end else begin
                    ras_q[RAS_DEPTH-1] <= commit_link_i;
                end
            end else if (commit_return_i && ras_count_q != 0) begin
                ras_count_q <= ras_count_q - 1'b1;
            end
        end
    end

`ifndef SYNTHESIS
    initial begin
        assert (ENTRIES >= 2 && (ENTRIES & (ENTRIES - 1)) == 0);
        assert (RAS_DEPTH >= 2 && (RAS_DEPTH & (RAS_DEPTH - 1)) == 0);
    end
`endif
endmodule
