`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: fetch_queue
// Generated: 2026-07-13
// Source: 053 architecture
module fetch_queue #(
    parameter int unsigned DEPTH = core_config_pkg::FETCH_QUEUE_DEPTH
) (
    input  logic clk,
    input  logic rst,
    input  logic flush_i,
    input  logic push_i,
    input  core_types_pkg::fetch_entry_t push_entry_i,
    input  logic pop_i,
    output logic valid_o,
    output core_types_pkg::fetch_entry_t head_o,
    output logic [$clog2(DEPTH + 1)-1:0] count_o
);
    localparam int unsigned PTR_W = $clog2(DEPTH);
    typedef logic [PTR_W-1:0] ptr_t;
    typedef logic [$clog2(DEPTH + 1)-1:0] count_t;

    core_types_pkg::fetch_entry_t entries_q [0:DEPTH-1];
    ptr_t head_q, tail_q;
    count_t count_q;

    assign valid_o = count_q != 0;
    assign head_o = entries_q[head_q];
    assign count_o = count_q;

    always_ff @(posedge clk) begin
        if (rst || flush_i) begin
            head_q <= '0;
            tail_q <= '0;
            count_q <= '0;
        end else begin
            if (push_i) begin
                entries_q[tail_q] <= push_entry_i;
                tail_q <= tail_q + 1'b1;
            end
            if (pop_i) head_q <= head_q + 1'b1;
            unique case ({push_i, pop_i})
                2'b10: count_q <= count_q + 1'b1;
                2'b01: count_q <= count_q - 1'b1;
                default: begin end
            endcase
        end
    end

`ifndef SYNTHESIS
    always_ff @(posedge clk) begin
        if (!rst && !flush_i) begin
            assert (count_q <= count_t'(DEPTH));
            if (push_i && !pop_i) assert (count_q < count_t'(DEPTH));
            if (pop_i) assert (count_q != 0);
        end
    end
`endif
endmodule
