`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: fetch_queue
// Generated: 2026-07-13
// Source: 053 architecture
module fetch_queue #(
    parameter int unsigned DEPTH = core_config_pkg::FETCH_QUEUE_DEPTH
) (
    input  logic clk,
    input  logic rst,
    input  logic flush_i,
    input  logic push_i,
    input  core_types_pkg::fetch_entry_t push_entry_i,
    input  logic pop_i,
    output logic valid_o,
    output core_types_pkg::fetch_entry_t head_o,
    output logic [$clog2(DEPTH + 1)-1:0] count_o
);
    typedef logic [$clog2(DEPTH + 1)-1:0] count_t;

    core_types_pkg::fetch_entry_t entries_q [0:DEPTH-1];
    core_types_pkg::fetch_entry_t entries_d [0:DEPTH-1];
    count_t count_q;
    integer comb_i;
    integer seq_i;

    assign valid_o = count_q != 0;
    // Keep the dispatch payload on a fixed bank of flops.  The former
    // entries_q[head_q] read inferred a wide distributed-RAM mux from the
    // head pointer into decode, scoreboard allocation and IQ enqueue.
    assign head_o = entries_q[0];
    assign count_o = count_q;

    always_comb begin
        for (comb_i = 0; comb_i < DEPTH; comb_i = comb_i + 1)
            entries_d[comb_i] = entries_q[comb_i];

        if (pop_i) begin
            for (comb_i = 0; comb_i < DEPTH - 1; comb_i = comb_i + 1)
                entries_d[comb_i] = entries_q[comb_i + 1];
        end

        if (push_i) begin
            if (pop_i)
                entries_d[count_q - 1'b1] = push_entry_i;
            else
                entries_d[count_q] = push_entry_i;
        end
    end

    always_ff @(posedge clk) begin
        if (rst || flush_i) begin
            count_q <= '0;
        end else begin
            for (seq_i = 0; seq_i < DEPTH; seq_i = seq_i + 1)
                entries_q[seq_i] <= entries_d[seq_i];
            unique case ({push_i, pop_i})
                2'b10: count_q <= count_q + 1'b1;
                2'b01: count_q <= count_q - 1'b1;
                default: begin end
            endcase
        end
    end

`ifndef SYNTHESIS
    always_ff @(posedge clk) begin
        if (!rst && !flush_i) begin
            assert (count_q <= count_t'(DEPTH));
            if (push_i && !pop_i) assert (count_q < count_t'(DEPTH));
            if (pop_i) assert (count_q != 0);
        end
    end
`endif
endmodule
