`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: csr_file
// Generated: 2026-07-13
// Source: 053 architecture + current rv32mi contract
module csr_file (
    input  logic        clk,
    input  logic        rst,
    input  logic [11:0] read_addr_i,
    output logic [31:0] read_data_o,
    input  logic        write_valid_i,
    input  logic [11:0] write_addr_i,
    input  logic [31:0] write_data_i,
    input  logic        trap_valid_i,
    input  logic [31:0] trap_pc_i,
    input  logic [4:0]  trap_cause_i,
    input  logic [31:0] trap_tval_i,
    input  logic        mret_valid_i,
    input  logic [63:0] cycle_i,
    input  logic [63:0] instret_i,
    output logic [31:0] mtvec_o,
    output logic [31:0] mepc_o
);
    logic [31:0] mstatus_q, mtvec_q, mscratch_q, mepc_q, mcause_q, mtval_q;

    assign mtvec_o = {mtvec_q[31:2], 2'b00};
    assign mepc_o  = {mepc_q[31:2], 2'b00};

    always_comb begin
        read_data_o = 32'd0;
        unique case (read_addr_i)
            12'h300: read_data_o = mstatus_q;
            12'h301: read_data_o = 32'h4000_1100;
            12'h305: read_data_o = mtvec_q;
            12'h340: read_data_o = mscratch_q;
            12'h341: read_data_o = mepc_q;
            12'h342: read_data_o = mcause_q;
            12'h343: read_data_o = mtval_q;
            12'hC00: read_data_o = cycle_i[31:0];
            12'hC80: read_data_o = cycle_i[63:32];
            12'hC02: read_data_o = instret_i[31:0];
            12'hC82: read_data_o = instret_i[63:32];
            12'hF14: read_data_o = 32'd0;
            default: read_data_o = 32'd0;
        endcase
    end

    always_ff @(posedge clk) begin
        if (rst) begin
            mstatus_q  <= 32'h0000_1800;
            mtvec_q    <= 32'd0;
            mscratch_q <= 32'd0;
            mepc_q     <= 32'd0;
            mcause_q   <= 32'd0;
            mtval_q    <= 32'd0;
        end else if (trap_valid_i) begin
            mepc_q <= {trap_pc_i[31:2], 2'b00};
            mcause_q <= {27'd0, trap_cause_i};
            mtval_q <= trap_tval_i;
            mstatus_q[7] <= mstatus_q[3];
            mstatus_q[3] <= 1'b0;
            mstatus_q[12:11] <= 2'b11;
        end else begin
            if (mret_valid_i) begin
                mstatus_q[3] <= mstatus_q[7];
                mstatus_q[7] <= 1'b1;
                mstatus_q[12:11] <= 2'b00;
            end
            if (write_valid_i) begin
                unique case (write_addr_i)
                    12'h300: mstatus_q <= write_data_i;
                    12'h305: mtvec_q <= {write_data_i[31:2], 2'b00};
                    12'h340: mscratch_q <= write_data_i;
                    12'h341: mepc_q <= {write_data_i[31:2], 2'b00};
                    12'h342: mcause_q <= write_data_i;
                    12'h343: mtval_q <= write_data_i;
                    default: begin end
                endcase
            end
        end
    end
endmodule
