`timescale 1ns / 1ps
// Auto-generated by frontend-rtl-gen
// Design: superScalar in-order single-issue core
// Module: dcache
// Generated: 2026-07-13
// Source: 053 architecture
module dcache #(
    parameter int unsigned LINE_COUNT = core_config_pkg::DCACHE_LINES,
    parameter logic [31:0] CACHE_START = core_config_pkg::DRAM_START,
    parameter logic [31:0] CACHE_END   = core_config_pkg::DRAM_END
) (
    input  logic clk,
    input  logic rst,
    input  logic kill_i,
    input  logic cpu_req_valid_i,
    output logic cpu_req_ready_o,
    input  logic cpu_req_write_i,
    input  logic [31:0] cpu_req_addr_i,
    input  logic [31:0] cpu_req_wdata_i,
    input  logic [3:0] cpu_req_wstrb_i,
    input  logic cpu_req_uncached_i,
    output logic cpu_resp_valid_o,
    output logic [31:0] cpu_resp_rdata_o,
    output logic mem_req_valid_o,
    input  logic mem_req_ready_i,
    output logic mem_req_write_o,
    output logic [31:0] mem_req_addr_o,
    output logic [31:0] mem_req_wdata_o,
    output logic [3:0] mem_req_wstrb_o,
    output logic mem_req_uncached_o,
    input  logic mem_resp_valid_i,
    input  logic [31:0] mem_resp_rdata_i,
    output logic access_pulse_o,
    output logic miss_pulse_o,
    output logic idle_o
);
    localparam int unsigned INDEX_W = $clog2(LINE_COUNT);
    localparam int unsigned TAG_LSB = 4 + INDEX_W;
    // CACHE_END is exclusive and the cacheable DRAM window is naturally
    // aligned.  Bits above CACHE_ADDR_W are already checked by cacheable_c,
    // so only the remaining local alias bits belong in the tag RAM.
    localparam int unsigned CACHE_ADDR_W = $clog2(CACHE_END - CACHE_START);
    localparam int unsigned TAG_W = CACHE_ADDR_W - TAG_LSB;

    typedef enum logic [2:0] {
        DC_INIT, DC_IDLE, DC_UNC_REQ, DC_UNC_WAIT, DC_REFILL_REQ, DC_REFILL_WAIT
    } state_e;
    state_e state_q;

    // Valid and tag share one synchronous BRAM.  The dedicated bank module
    // exposes one physical write port, allowing Vivado to honor ram_style=block
    // while DC_INIT still invalidates one line per cycle.
    logic [TAG_W:0] tag_read_data;
    logic tag_write_en;
    logic [INDEX_W-1:0] tag_write_index;
    logic [TAG_W:0] tag_write_data;
    logic [INDEX_W-1:0] init_index_q;
    logic [31:0] req_addr_q;
    logic [1:0] fill_word_q, refill_count_q;
    logic [31:0] resp_data_q;
    logic resp_valid_q;
    logic lookup_valid_q;
    logic lookup_write_q;
    logic [31:0] lookup_addr_q;
    logic [CACHE_ADDR_W-1:TAG_LSB] lookup_tag_q;
    logic [INDEX_W-1:0] lookup_index_q;
    logic [1:0] lookup_word_q;
    logic [31:0] lookup_store_data_q;
    logic [3:0] lookup_store_mask_q;
    logic killed_q;

    logic bank_read_en;
    logic [INDEX_W-1:0] bank_read_index;
    logic [31:0] bank_read_data [0:3];
    logic bank_write_en;
    logic [INDEX_W-1:0] bank_write_index;
    logic [1:0] bank_write_word;
    logic [31:0] bank_write_data;
    logic [3:0] bank_write_mask;
    logic cacheable_c, lookup_hit_c, lookup_load_miss_c, lookup_stall_c;
    logic victim_invalidate_c;
    logic metadata_read_en;
    logic [INDEX_W-1:0] index_c;
    logic [CACHE_ADDR_W-1:TAG_LSB] tag_c;
    logic [1:0] word_c;
    logic [31:0] store_aligned_data_c;
    logic [3:0] store_aligned_mask_c;

    // CACHE_START..CACHE_END is the naturally aligned 256 KiB SoC DRAM
    // window.  Decode its fixed upper bits instead of synthesizing two
    // 32-bit magnitude comparators on the load-address critical path.
    assign cacheable_c = !cpu_req_uncached_i &&
                         cpu_req_addr_i[31:18] == CACHE_START[31:18];
    assign index_c = cpu_req_addr_i[TAG_LSB-1:4];
    assign tag_c   = cpu_req_addr_i[CACHE_ADDR_W-1:TAG_LSB];
    assign word_c  = cpu_req_addr_i[3:2];
    assign lookup_hit_c = lookup_valid_q && tag_read_data[TAG_W] &&
                          tag_read_data[TAG_W-1:0] == lookup_tag_q;
    assign lookup_load_miss_c = lookup_valid_q && !lookup_write_q && !lookup_hit_c;
    // Refill data writes the victim bank one word at a time.  Invalidate the
    // old tag before the first word can arrive, so a killed partial refill can
    // never expose new-line data through the victim's still-valid old tag.
    assign victim_invalidate_c = state_q == DC_IDLE && lookup_load_miss_c;
    // A store lookup occupies one extra cycle so its cache update reaches the
    // data RAM before a following load can observe that word.
    assign lookup_stall_c = lookup_valid_q && (lookup_write_q || !lookup_hit_c);
    assign metadata_read_en = state_q == DC_IDLE && cpu_req_valid_i && cacheable_c;
    assign store_aligned_data_c = cpu_req_wdata_i << {cpu_req_addr_i[1:0], 3'b000};
    assign store_aligned_mask_c = (cpu_req_wstrb_i << cpu_req_addr_i[1:0]) & 4'hf;
    assign idle_o = state_q == DC_IDLE;

    // Initialization, victim invalidation and the last refill beat occur in
    // mutually exclusive states and therefore share the single tag RAM write
    // port without changing its inference template.
    assign tag_write_en = state_q == DC_INIT ||
                          victim_invalidate_c ||
                          (state_q == DC_REFILL_WAIT && mem_resp_valid_i &&
                           !killed_q && !kill_i && refill_count_q == 2'd3);
    assign tag_write_index = state_q == DC_INIT ? init_index_q :
                             victim_invalidate_c ? lookup_index_q :
                             req_addr_q[TAG_LSB-1:4];
    assign tag_write_data = (state_q == DC_INIT || victim_invalidate_c) ? '0 :
                            {1'b1, req_addr_q[CACHE_ADDR_W-1:TAG_LSB]};

    dcache_tag_bank #(
        .LINE_COUNT(LINE_COUNT), .TAG_WIDTH(TAG_W + 1)
    ) u_tag_bank (
        .clk(clk), .read_en_i(metadata_read_en), .read_index_i(index_c),
        .read_data_o(tag_read_data), .write_en_i(tag_write_en),
        .write_index_i(tag_write_index), .write_data_i(tag_write_data)
    );

    genvar bank;
    generate
        for (bank = 0; bank < 4; bank = bank + 1) begin : g_data_bank
            localparam logic [1:0] BANK_WORD = bank;
            dcache_data_bank #(.LINE_COUNT(LINE_COUNT)) u_data_bank (
                .clk(clk), .read_en_i(bank_read_en),
                .read_index_i(bank_read_index), .read_data_o(bank_read_data[bank]),
                .write_en_i(bank_write_en && bank_write_word == BANK_WORD),
                .write_index_i(bank_write_index), .write_data_i(bank_write_data),
                .write_mask_i(bank_write_mask)
            );
        end
    endgenerate

    always_comb begin
        // Start the synchronous data-array lookup speculatively.  Read enable
        // is independent of tag/range comparison and therefore cannot inherit
        // their delay.  Data from a request that is not accepted is ignored.
        bank_read_en = state_q == DC_IDLE && cpu_req_valid_i &&
                       !cpu_req_write_i;
        bank_read_index = index_c;
        bank_write_en = 1'b0;
        bank_write_index = lookup_index_q;
        bank_write_word = lookup_word_q;
        bank_write_data = lookup_store_data_q;
        bank_write_mask = lookup_store_mask_q;
        if (lookup_valid_q && lookup_write_q && lookup_hit_c) begin
            bank_write_en = 1'b1;
        end else if (state_q == DC_REFILL_WAIT && mem_resp_valid_i &&
                     !killed_q && !kill_i) begin
            bank_write_en = 1'b1;
            bank_write_index = req_addr_q[TAG_LSB-1:4];
            bank_write_word = fill_word_q;
            bank_write_data = mem_resp_rdata_i;
            bank_write_mask = 4'hf;
        end
    end

    always_comb begin
        cpu_req_ready_o = 1'b0;
        cpu_resp_valid_o = (resp_valid_q ||
                            (lookup_valid_q && !lookup_write_q && lookup_hit_c)) &&
                           !kill_i;
        cpu_resp_rdata_o = (lookup_valid_q && !lookup_write_q && lookup_hit_c) ?
                           bank_read_data[lookup_word_q] : resp_data_q;
        mem_req_valid_o = 1'b0;
        mem_req_write_o = 1'b0;
        mem_req_addr_o = 32'd0;
        mem_req_wdata_o = 32'd0;
        mem_req_wstrb_o = 4'd0;
        mem_req_uncached_o = 1'b0;
        access_pulse_o = 1'b0;
        miss_pulse_o = 1'b0;

        unique case (state_q)
            DC_IDLE: begin
                if (lookup_stall_c) begin
                    // The preceding synchronous metadata lookup missed.  No
                    // younger request may be accepted until refill owns the
                    // single memory port.
                    miss_pulse_o = lookup_load_miss_c;
                end else if (cpu_req_valid_i) begin
                    if (cpu_req_write_i) begin
                        mem_req_valid_o = 1'b1;
                        mem_req_write_o = 1'b1;
                        mem_req_addr_o = cpu_req_addr_i;
                        mem_req_wdata_o = cpu_req_wdata_i;
                        mem_req_wstrb_o = cpu_req_wstrb_i;
                        mem_req_uncached_o = !cacheable_c;
                        cpu_req_ready_o = mem_req_ready_i;
                        access_pulse_o = cacheable_c && mem_req_ready_i;
                    end else begin
                        if (cacheable_c) begin
                            cpu_req_ready_o = 1'b1;
                            access_pulse_o = 1'b1;
                        end else begin
                            // Capture an uncached load locally first.  Issuing
                            // it from DC_UNC_REQ on the next cycle prevents the
                            // Load Queue/arbitration cone from reaching the
                            // Core/SoC register-slice capture enable.
                            cpu_req_ready_o = 1'b1;
                        end
                    end
                end
            end
            DC_UNC_REQ: begin
                mem_req_valid_o = 1'b1;
                mem_req_write_o = 1'b0;
                mem_req_addr_o = {req_addr_q[31:2], 2'b00};
                mem_req_uncached_o = 1'b1;
            end
            DC_REFILL_REQ: begin
                mem_req_valid_o = 1'b1;
                mem_req_write_o = 1'b0;
                mem_req_addr_o = {req_addr_q[31:4], 4'b0000} + {28'd0, fill_word_q, 2'b00};
                mem_req_uncached_o = 1'b0;
            end
            default: begin end
        endcase
    end

    always_ff @(posedge clk) begin
        if (rst) begin
            state_q <= DC_INIT;
            init_index_q <= '0;
            req_addr_q <= '0;
            fill_word_q <= '0;
            refill_count_q <= '0;
            resp_data_q <= '0;
            resp_valid_q <= 1'b0;
            lookup_valid_q <= 1'b0;
            lookup_write_q <= 1'b0;
            lookup_addr_q <= '0;
            lookup_tag_q <= '0;
            lookup_index_q <= '0;
            lookup_word_q <= '0;
            lookup_store_data_q <= '0;
            lookup_store_mask_q <= '0;
            killed_q <= 1'b0;
        end else begin
            // Responses are one-cycle events.  Keeping the cache in DC_IDLE on
            // a hit permits a new request to replace the completing load.
            resp_valid_q <= 1'b0;
            lookup_valid_q <= 1'b0;
            if (kill_i && state_q != DC_IDLE) killed_q <= 1'b1;
            unique case (state_q)
                DC_INIT: begin
                    if (init_index_q == INDEX_W'(LINE_COUNT - 1)) begin
                        init_index_q <= '0;
                        state_q <= DC_IDLE;
                    end else begin
                        init_index_q <= init_index_q + 1'b1;
                    end
                end
                DC_IDLE: begin
                    killed_q <= 1'b0;
                    if (lookup_load_miss_c) begin
                        req_addr_q <= lookup_addr_q;
                        fill_word_q <= lookup_word_q;
                        refill_count_q <= 2'd0;
                        state_q <= DC_REFILL_REQ;
                    end else if (!lookup_stall_c && cpu_req_valid_i && cpu_req_ready_o) begin
                        if (cacheable_c) begin
                            lookup_valid_q <= 1'b1;
                            lookup_write_q <= cpu_req_write_i;
                            lookup_addr_q <= cpu_req_addr_i;
                            lookup_tag_q <= tag_c;
                            lookup_index_q <= index_c;
                            lookup_word_q <= word_c;
                            lookup_store_data_q <= store_aligned_data_c;
                            lookup_store_mask_q <= store_aligned_mask_c;
                        end else if (!cpu_req_write_i) begin
                            req_addr_q <= cpu_req_addr_i;
                            state_q <= DC_UNC_REQ;
                        end
                    end
                end
                DC_UNC_REQ: begin
                    if (kill_i) begin
                        // The request is visible to the slice in this state.
                        // If accepted together with kill, drain its response;
                        // otherwise cancel it before it leaves the DCache.
                        if (mem_req_ready_i) begin
                            state_q <= DC_UNC_WAIT;
                            killed_q <= 1'b1;
                        end else begin
                            state_q <= DC_IDLE;
                            killed_q <= 1'b0;
                        end
                    end else if (mem_req_ready_i) begin
                        state_q <= DC_UNC_WAIT;
                    end
                end
                DC_UNC_WAIT: begin
                    if (mem_resp_valid_i) begin
                        if (!killed_q && !kill_i) begin
                            resp_data_q <= mem_resp_rdata_i;
                            resp_valid_q <= 1'b1;
                            state_q <= DC_IDLE;
                        end else begin
                            state_q <= DC_IDLE;
                            killed_q <= 1'b0;
                        end
                    end
                end
                DC_REFILL_REQ: begin
                    if (kill_i) begin
                        // If memory accepted the request on the same edge as the
                        // kill, retain ownership until its late response drains.
                        // Otherwise the request was cancelled before acceptance.
                        if (mem_req_ready_i) begin
                            state_q <= DC_REFILL_WAIT;
                            killed_q <= 1'b1;
                        end else begin
                            state_q <= DC_IDLE;
                            killed_q <= 1'b0;
                        end
                    end else if (mem_req_ready_i) begin
                        state_q <= DC_REFILL_WAIT;
                    end
                end
                DC_REFILL_WAIT: begin
                    if (mem_resp_valid_i) begin
                        if (killed_q || kill_i) begin
                            state_q <= DC_IDLE;
                            killed_q <= 1'b0;
                        end else begin
                            if (refill_count_q == 2'd0) begin
                                resp_data_q <= mem_resp_rdata_i;
                                resp_valid_q <= 1'b1;
                            end
                            if (refill_count_q == 2'd3) begin
                                state_q <= DC_IDLE;
                            end else begin
                                fill_word_q <= fill_word_q + 1'b1;
                                refill_count_q <= refill_count_q + 1'b1;
                                state_q <= DC_REFILL_REQ;
                            end
                        end
                    end
                end
                default: state_q <= DC_IDLE;
            endcase
        end
    end
endmodule
